In [1]:
from pbase.config.ray import init_ray
import shadow_price_prediction

# Initialize Ray for parallel processing
extra_modules = [shadow_price_prediction]
init_ray(address='ray://10.8.0.36:10001', extra_modules=extra_modules)

import pandas as pd
import numpy as np
import random
from pathlib import Path
from pbase.utils.ray import parallel_equal_pool

# Import tuning utilities for resumable search
from shadow_price_prediction.tuning_utils import (
    load_previous_params,
    sample_params,
    run_single_experiment
)

pd.set_option('display.max_columns', 99)

2025-11-22 23:34:28,011	INFO client_builder.py:242 -- Passing the following kwargs to ray.init() on the server: log_to_driver
2025-11-22 23:34:28,357	INFO packaging.py:588 -- Creating a file package for local module '/home/xyz/workspace/research-spice-shadow-price-pred/src/shadow_price_prediction'.
2025-11-22 23:34:28,366	INFO packaging.py:380 -- Pushing file package 'gcs://_ray_pkg_00c06ac0702a0e27.zip' (0.53MiB) to Ray cluster...
2025-11-22 23:34:28,372	INFO packaging.py:393 -- Successfully pushed file package 'gcs://_ray_pkg_00c06ac0702a0e27.zip'.

In [2]:
N_ITER = 10000  # Total number of experiments to run (including previous ones)
BASE_OUTPUT_DIR = Path('/opt/temp/haoyan/param_search_new')

## 5. Analyze Best Results

In [3]:
metrics_dir = BASE_OUTPUT_DIR / 'metrics'

if metrics_dir.exists():
    all_metrics = []
    for file in metrics_dir.glob('iter_*.parquet'):
        try:
            df = pd.read_parquet(file)
            all_metrics.append(df)
        except Exception as e:
            print(f"Warning: Could not load {file.name}: {e}")
    
    if all_metrics:
        combined_metrics = pd.concat(all_metrics, ignore_index=True)
        
        print(f"Total runs analyzed: {len(combined_metrics)}")
        
        # Best by F1 Score
        if 'F1' in combined_metrics.columns:
            best_idx = combined_metrics['F1'].idxmax()
            best_result = combined_metrics.iloc[best_idx]
            
            print("\n" + "=" * 60)
            print("Best Run (by F1 Score)")
            print("=" * 60)
            print(f"Iteration: {best_result.get('iteration', 'N/A')}")
            print(f"F1 Score: {best_result['F1']:.4f}")
            if 'MAE' in best_result:
                print(f"MAE: {best_result['MAE']:.4f}")
            if 'Precision' in best_result:
                print(f"Precision: {best_result['Precision']:.4f}")
            if 'Recall' in best_result:
                print(f"Recall: {best_result['Recall']:.4f}")
            
            # Print parameters
            print("\nParameters:")
            param_cols = [col for col in combined_metrics.columns 
                         if col not in ['F1', 'Precision', 'Recall', 'MAE', 'RMSE', 'R2',
                                       'iteration', 'timestamp', 'run_id', 'metrics_file',
                                       'per_outage_file', 'agg_file']]
            for col in param_cols:
                print(f"  {col}: {best_result[col]}")
        
        # Best by MAE (lower is better)
        if 'MAE' in combined_metrics.columns:
            best_idx = combined_metrics['MAE'].idxmin()
            best_result = combined_metrics.iloc[best_idx]
            
            print("\n" + "=" * 60)
            print("Best Run (by MAE)")
            print("=" * 60)
            print(f"Iteration: {best_result.get('iteration', 'N/A')}")
            print(f"MAE: {best_result['MAE']:.4f}")
            if 'F1' in best_result:
                print(f"F1 Score: {best_result['F1']:.4f}")
            if 'RMSE' in best_result:
                print(f"RMSE: {best_result['RMSE']:.4f}")
            
            # Print parameters
            print("\nParameters:")
            for col in param_cols:
                print(f"  {col}: {best_result[col]}")

Total runs analyzed: 588

## 6. View Results Summary

In [ ]:
x = pd.read_parquet(combined_metrics.sort_values('f1_score', ascending=False).loc[3]['agg_file'])
cols = ['90_diff', '105_diff', '95_diff', '100_diff', 'curvature_100', '60_diff', 'prob_overload', '90_diff', '85_diff', '100_diff', '70_diff', '95_diff', 'prob_exceed_100', '80_diff', 'prob_exceed_90', '105', 'log_density_100', '110', 'risk_ratio', 'actual_shadow_price', 'predicted_shadow_price', 'binding_probability', 'predicted_binding_count']
x = x[x['predicted_binding_count'] >= 1].sort_values(['predicted_shadow_price', 'binding_probability', 'predicted_binding_count'], ascending=[False, False, False]).drop_duplicates(subset=['auction_month', 'branch_name'])
print(x.groupby('auction_month').size())
x[cols].corr(method='pearson')['actual_shadow_price'].sort_values(ascending=False)

auction_month
2025-07-01    490
2025-08-01    382
2025-09-01    626
2025-10-01    632
dtype: int64

actual_shadow_price        1.000000
predicted_shadow_price     0.300131
predicted_binding_count    0.181142
binding_probability        0.159086
log_density_100            0.107246
105_diff                   0.098622
105                        0.098395
110                        0.097264
100_diff                   0.097205
100_diff                   0.097205
95_diff                    0.095053
95_diff                    0.095053
90_diff                    0.090839
90_diff                    0.090839
prob_exceed_90             0.088875
85_diff                    0.084683
80_diff                    0.081388
70_diff                    0.079735
prob_overload              0.075787
prob_exceed_100            0.075787
60_diff                    0.067397
curvature_100              0.009775
risk_ratio                -0.016389
Name: actual_shadow_price, dtype: float64

In [ ]:
a = x[x['auction_month']=='2025-10']
a[a['branch_name'].str.contains('aust', case=False)]

,,branch_name,log_density_100,80_diff,prob_exceed_100,curvature_100,100_diff,85_diff,60_diff,100,105,70_diff,90,prob_exceed_90,110,prob_overload,95_diff,risk_ratio,90_diff,105_diff,95,actual_shadow_price,predicted_shadow_price,binding_probability,binding_probability_scaled,threshold,predicted_binding_count,actual_binding,auction_month,market_month,predicted_binding,error,abs_error,model_used
constraint_id,flow_direction,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
316316,1,AUST_TAYS_1545 A,3.769987,2.364259,4.119607,0.135582,3.476634,2.682441,1.146306,3.200974,3.671965,1.787645,2.78819,4.073361,3.827148,4.119607,3.161357,-0.002453,2.913186,3.871775,2.952014,2950.54,7662.726562,0.738490,0.0,0.5,9,1,2025-10-01,2025-10-01,True,4712.186562,4712.186562,Default
316680,1,MAUSTHLT69_1 1,-0.247172,-0.241334,-0.180466,-0.028706,-0.217223,-0.241286,-0.175316,-0.215049,-0.209627,-0.238180,-0.23788,-0.217988,-0.173675,-0.180466,-0.227935,-0.002475,-0.236435,-0.199252,-0.225976,0.00,1429.236694,0.267182,0.0,0.5,2,0,2025-10-01,2025-10-01,True,1429.236694,1429.236694,Default

In [ ]:
if 'combined_metrics' in locals():
    # Display summary statistics
    print("Summary Statistics:")
    print("=" * 60)
    
    metric_cols = ['f1_score', 'precision', 'recall', 'mae', 'rmse']
    available_metrics = [col for col in metric_cols if col in combined_metrics.columns]
    
    summary = combined_metrics[available_metrics].describe()
    print(summary)
    
    # Optionally display the top 5 runs by F1
    if 'F1' in combined_metrics.columns:
        print("\n" + "=" * 60)
        print("Top 5 Runs by F1 Score")
        print("=" * 60)
        
        display_cols = ['iteration'] + available_metrics
        top5 = combined_metrics.nlargest(5, 'F1')[display_cols]
        print(top5.to_string(index=False))

Summary Statistics:
============================================================
         f1_score   precision      recall         mae         rmse
count  588.000000  588.000000  588.000000  588.000000   588.000000
mean     0.340072    0.329733    0.351464  327.264258  1847.983187
std      0.013587    0.007486    0.020915    6.099367    70.495382
min      0.267990    0.295821    0.244945  313.298755  1745.457301
25%      0.337177    0.325526    0.348291  322.538323  1807.515468
50%      0.343159    0.330924    0.356473  327.209863  1834.725888
75%      0.348021    0.335002    0.363613  331.394778  1865.876581
max      0.359390    0.344974    0.378987  346.003628  2196.036819

In [ ]:
# import shutil

# shutil.rmtree(BASE_OUTPUT_DIR)

In [4]:
import pandas as pd
from shadow_price_prediction.config import PredictionConfig
from shadow_price_prediction.tuning_utils import update_config_with_params
from shadow_price_prediction.pipeline import ShadowPricePipeline

def create_pipeline_from_row(row):
    """
    Create a ShadowPricePipeline using the parameters from a single row of results.
    
    Args:
        row: DataFrame row with parameters
    
    Returns:
        ShadowPricePipeline configured with the parameters
    """
    params_dict = row.to_dict()
        
    print("Initializing pipeline with selected parameters:")
    for k, v in params_dict.items():
        if k.startswith(('clf_', 'reg_', 'threshold_', 'label_')):
             print(f"  {k}: {v}")

    # Create Config
    config = PredictionConfig()
    
    # Update Config with Params
    config = update_config_with_params(config, params_dict)
    
    # Initialize Pipeline
    pipeline = ShadowPricePipeline(config)
    
    return pipeline

In [33]:
params = combined_metrics.sort_values('f1_score', ascending=False).iloc[0]
params['clf_xgb_n_estimators'] = 1000
params['reg_xgb_n_estimators'] = 1000
params['reg_xgb_max_depth'] = 7
params['clf_xgb_max_depth'] = 7
# params['reg_xgb_max_depth'] = 2
# params['clf_xgb_max_depth'] = 2
params['label_threshold'] = 0
params['threshold_beta'] = 0.5
params['short_term_clf_xgb_w'] = 0.9
params['short_term_reg_xgb_w'] = 0.9
params['medium_term_clf_xgb_w'] = 0.7
params['medium_term_reg_xgb_w'] = 0.7
params['long_term_clf_xgb_w'] = 0.9
params['long_term_reg_xgb_w'] = 0.9


"""
clf_xgb_n_estimators: 500
clf_xgb_max_depth: 5
clf_xgb_learning_rate: 0.2
clf_xgb_gamma: 0.1
clf_xgb_min_child_weight: 10
clf_xgb_reg_alpha: 0.0
clf_xgb_reg_lambda: 100
reg_xgb_n_estimators: 500
reg_xgb_max_depth: 5
reg_xgb_learning_rate: 0.1
reg_xgb_gamma: 0.2
reg_xgb_min_child_weight: 10
reg_xgb_reg_alpha: 1.0
reg_xgb_reg_lambda: 1
threshold_beta: 1.0
clf_xgb_thres: 0.5
reg_xgb_thres: 0.5
"""

'\nclf_xgb_n_estimators: 500\nclf_xgb_max_depth: 5\nclf_xgb_learning_rate: 0.2\nclf_xgb_gamma: 0.1\nclf_xgb_min_child_weight: 10\nclf_xgb_reg_alpha: 0.0\nclf_xgb_reg_lambda: 100\nreg_xgb_n_estimators: 500\nreg_xgb_max_depth: 5\nreg_xgb_learning_rate: 0.1\nreg_xgb_gamma: 0.2\nreg_xgb_min_child_weight: 10\nreg_xgb_reg_alpha: 1.0\nreg_xgb_reg_lambda: 1\nthreshold_beta: 1.0\nclf_xgb_thres: 0.5\nreg_xgb_thres: 0.5\n'

In [34]:
pipeline = create_pipeline_from_row(params)

Initializing pipeline with selected parameters:
  clf_xgb_n_estimators: 1000
  clf_xgb_max_depth: 7
  clf_xgb_learning_rate: 0.2
  clf_xgb_gamma: 0.2
  clf_xgb_min_child_weight: 10
  clf_xgb_reg_alpha: 0.1
  clf_xgb_reg_lambda: 100
  reg_xgb_n_estimators: 1000
  reg_xgb_max_depth: 7
  reg_xgb_learning_rate: 0.1
  reg_xgb_gamma: 0.0
  reg_xgb_min_child_weight: 10
  reg_xgb_reg_alpha: 0.0
  reg_xgb_reg_lambda: 100
  threshold_beta: 0.5
  clf_xgb_thres: 0.5
  reg_xgb_thres: 0.5
  label_threshold: 0

In [35]:
test_periods = [
    (pd.Timestamp('2025-06-01'), pd.Timestamp('2025-06-01')),
    (pd.Timestamp('2025-07-01'), pd.Timestamp('2025-07-01')),
    (pd.Timestamp('2025-08-01'), pd.Timestamp('2025-08-01')),
    (pd.Timestamp('2025-09-01'), pd.Timestamp('2025-09-01')),
    (pd.Timestamp('2025-10-01'), pd.Timestamp('2025-10-01')),
    (pd.Timestamp('2025-11-01'), pd.Timestamp('2025-11-01')),
]

results_per_outage, final_results, metrics = pipeline.run(
    test_periods=test_periods,
    verbose=True,
    use_parallel=True,
    n_jobs=6,
)

================================================================================
SHADOW PRICE PREDICTION PIPELINE - PARALLEL PER-AUCTION-MONTH MODE
================================================================================
Total Test Periods: 6
Unique Auction Months: 6

  Auction: 2025-06 → 1 market month(s)
    - Market: 2025-06
  Auction: 2025-07 → 1 market month(s)
    - Market: 2025-07
  Auction: 2025-08 → 1 market month(s)
    - Market: 2025-08
  Auction: 2025-09 → 1 market month(s)
    - Market: 2025-09
  Auction: 2025-10 → 1 market month(s)
    - Market: 2025-10
  Auction: 2025-11 → 1 market month(s)
    - Market: 2025-11
Class Type: onpeak
Period Type: f0

🚀 Using Ray parallel processing for 6 auction months
   Workers: 6

================================================================================
[PARALLEL PROCESSING: Training and Predicting for All Auction Months]
================================================================================

(PoolActor pid=732223, ip=10.42.8.15) 25-11-23 00:07:00 EST | INFO    | dotenv.main          | _get_stream         | #61  | python-dotenv could not find configuration file .env.
(PoolActor pid=732223, ip=10.42.8.15) 25-11-23 00:07:00 EST | WARNING | pbase.utils.utils    | load_env            | #478 | .env could not be found...
(PoolActor pid=732223, ip=10.42.8.15) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | load_global_config  | #435 | Loading config from local cached json file...
(PoolActor pid=732223, ip=10.42.8.15) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | __init__            | #44  | Init global config...
(PoolActor pid=730680, ip=10.42.9.131) 25-11-23 00:07:00 EST | INFO    | dotenv.main          | _get_stream         | #61  | python-dotenv could not find configuration file .env.
(PoolActor pid=730680, ip=10.42.9.131) 25-11-23 00:07:00 EST | WARNING | pbase.utils.utils    | load_env            | #478 | .env could not be found...
(PoolActor pid=730680, ip=10.42.9.131) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | load_global_config  | #435 | Loading config from local cached json file...
(PoolActor pid=730680, ip=10.42.9.131) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | __init__            | #44  | Init global config...
(PoolActor pid=671348, ip=10.42.0.182) 25-11-23 00:07:00 EST | INFO    | dotenv.main          | _get_stream         | #61  | python-dotenv could not find configuration file .env.
(PoolActor pid=671348, ip=10.42.0.182) 25-11-23 00:07:00 EST | WARNING | pbase.utils.utils    | load_env            | #478 | .env could not be found...
(PoolActor pid=671348, ip=10.42.0.182) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | load_global_config  | #435 | Loading config from local cached json file...
(PoolActor pid=671348, ip=10.42.0.182) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | __init__            | #44  | Init global config...
(PoolActor pid=674818, ip=10.42.7.70) 25-11-23 00:07:00 EST | INFO    | dotenv.main          | _get_stream         | #61  | python-dotenv could not find configuration file .env.
(PoolActor pid=674818, ip=10.42.7.70) 25-11-23 00:07:00 EST | WARNING | pbase.utils.utils    | load_env            | #478 | .env could not be found...
(PoolActor pid=674818, ip=10.42.7.70) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | load_global_config  | #435 | Loading config from local cached json file...
(PoolActor pid=674818, ip=10.42.7.70) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | __init__            | #44  | Init global config...
(PoolActor pid=907599, ip=10.42.6.149) 25-11-23 00:07:00 EST | INFO    | dotenv.main          | _get_stream         | #61  | python-dotenv could not find configuration file .env.
(PoolActor pid=907599, ip=10.42.6.149) 25-11-23 00:07:00 EST | WARNING | pbase.utils.utils    | load_env            | #478 | .env could not be found...
(PoolActor pid=907599, ip=10.42.6.149) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | load_global_config  | #435 | Loading config from local cached json file...
(PoolActor pid=907599, ip=10.42.6.149) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | __init__            | #44  | Init global config...
(PoolActor pid=746008, ip=10.42.4.173) 25-11-23 00:07:00 EST | INFO    | dotenv.main          | _get_stream         | #61  | python-dotenv could not find configuration file .env.
(PoolActor pid=746008, ip=10.42.4.173) 25-11-23 00:07:00 EST | WARNING | pbase.utils.utils    | load_env            | #478 | .env could not be found...
(PoolActor pid=746008, ip=10.42.4.173) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | load_global_config  | #435 | Loading config from local cached json file...
(PoolActor pid=746008, ip=10.42.4.173) 25-11-23 00:07:00 EST | INFO    | pbase.config.base    | __init__            | #44  | Init global config...

(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) ================================================================================
(PoolActor pid=732223, ip=10.42.8.15) [Processing Auction Month: 2025-08]
(PoolActor pid=732223, ip=10.42.8.15)   Market Months: 1
(PoolActor pid=732223, ip=10.42.8.15)     - 2025-08
(PoolActor pid=732223, ip=10.42.8.15) ================================================================================
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) [STEP 1: Training Period Calculation]
(PoolActor pid=732223, ip=10.42.8.15)   Training Range: 2024-07 to 2025-07
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) [STEP 2: Loading Training Data]
(PoolActor pid=732223, ip=10.42.8.15)   Required period types: ['f0']
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) [Loading Training Data - Multi-Period Strategy]
(PoolActor pid=732223, ip=10.42.8.15) --------------------------------------------------------------------------------
(PoolActor pid=732223, ip=10.42.8.15)   Filtering to period types: ['f0']
(PoolActor pid=732223, ip=10.42.8.15) Training Window: 12 months
(PoolActor pid=732223, ip=10.42.8.15)   From: 2024-07
(PoolActor pid=732223, ip=10.42.8.15)   To:   2025-06
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2024-07...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 5 → 1 period types
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) ================================================================================
(PoolActor pid=907599, ip=10.42.6.149) [Processing Auction Month: 2025-06]
(PoolActor pid=907599, ip=10.42.6.149)   Market Months: 1
(PoolActor pid=907599, ip=10.42.6.149)     - 2025-06
(PoolActor pid=907599, ip=10.42.6.149) ================================================================================
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) [STEP 1: Training Period Calculation]
(PoolActor pid=907599, ip=10.42.6.149)   Training Range: 2024-05 to 2025-05
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) [STEP 2: Loading Training Data]
(PoolActor pid=907599, ip=10.42.6.149)   Required period types: ['f0']
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) [Loading Training Data - Multi-Period Strategy]
(PoolActor pid=907599, ip=10.42.6.149) --------------------------------------------------------------------------------
(PoolActor pid=907599, ip=10.42.6.149)   Filtering to period types: ['f0']
(PoolActor pid=907599, ip=10.42.6.149) Training Window: 12 months
(PoolActor pid=907599, ip=10.42.6.149)   From: 2024-05
(PoolActor pid=907599, ip=10.42.6.149)   To:   2025-04
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) Processing Auction: 2024-05...
(PoolActor pid=674818, ip=10.42.7.70)
(PoolActor pid=674818, ip=10.42.7.70) ================================================================================
(PoolActor pid=674818, ip=10.42.7.70) [Processing Auction Month: 2025-11]
(PoolActor pid=674818, ip=10.42.7.70)   Market Months: 1
(PoolActor pid=674818, ip=10.42.7.70)     - 2025-11
(PoolActor pid=674818, ip=10.42.7.70) ================================================================================
(PoolActor pid=674818, ip=10.42.7.70)
(PoolActor pid=674818, ip=10.42.7.70) [STEP 1: Training Period Calculation]
(PoolActor pid=674818, ip=10.42.7.70)   Training Range: 2024-10 to 2025-10
(PoolActor pid=674818, ip=10.42.7.70)
(PoolActor pid=674818, ip=10.42.7.70) [STEP 2: Loading Training Data]
(PoolActor pid=674818, ip=10.42.7.70)   Required period types: ['f0']
(PoolActor pid=674818, ip=10.42.7.70)
(PoolActor pid=674818, ip=10.42.7.70) [Loading Training Data - Multi-Period Strategy]
(PoolActor pid=674818, ip=10.42.7.70) --------------------------------------------------------------------------------
(PoolActor pid=674818, ip=10.42.7.70)   Filtering to period types: ['f0']
(PoolActor pid=674818, ip=10.42.7.70) Training Window: 12 months
(PoolActor pid=674818, ip=10.42.7.70)   From: 2024-10
(PoolActor pid=674818, ip=10.42.7.70)   To:   2025-09
(PoolActor pid=674818, ip=10.42.7.70)
(PoolActor pid=674818, ip=10.42.7.70) Processing Auction: 2024-10...
(PoolActor pid=674818, ip=10.42.7.70)   Filtered: 4 → 1 period types
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) ================================================================================
(PoolActor pid=730680, ip=10.42.9.131) [Processing Auction Month: 2025-07]
(PoolActor pid=730680, ip=10.42.9.131)   Market Months: 1
(PoolActor pid=730680, ip=10.42.9.131)     - 2025-07
(PoolActor pid=730680, ip=10.42.9.131) ================================================================================
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) [STEP 1: Training Period Calculation]
(PoolActor pid=730680, ip=10.42.9.131)   Training Range: 2024-06 to 2025-06
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) [STEP 2: Loading Training Data]
(PoolActor pid=730680, ip=10.42.9.131)   Required period types: ['f0']
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) [Loading Training Data - Multi-Period Strategy]
(PoolActor pid=730680, ip=10.42.9.131) --------------------------------------------------------------------------------
(PoolActor pid=730680, ip=10.42.9.131)   Filtering to period types: ['f0']
(PoolActor pid=730680, ip=10.42.9.131) Training Window: 12 months
(PoolActor pid=730680, ip=10.42.9.131)   From: 2024-06
(PoolActor pid=730680, ip=10.42.9.131)   To:   2025-05
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) Processing Auction: 2024-06...
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) ================================================================================
(PoolActor pid=671348, ip=10.42.0.182) [Processing Auction Month: 2025-09]
(PoolActor pid=671348, ip=10.42.0.182)   Market Months: 1
(PoolActor pid=671348, ip=10.42.0.182)     - 2025-09
(PoolActor pid=671348, ip=10.42.0.182) ================================================================================
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) [STEP 1: Training Period Calculation]
(PoolActor pid=671348, ip=10.42.0.182)   Training Range: 2024-08 to 2025-08
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) [STEP 2: Loading Training Data]
(PoolActor pid=671348, ip=10.42.0.182)   Required period types: ['f0']
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) [Loading Training Data - Multi-Period Strategy]
(PoolActor pid=671348, ip=10.42.0.182) --------------------------------------------------------------------------------
(PoolActor pid=671348, ip=10.42.0.182)   Filtering to period types: ['f0']
(PoolActor pid=671348, ip=10.42.0.182) Training Window: 12 months
(PoolActor pid=671348, ip=10.42.0.182)   From: 2024-08
(PoolActor pid=671348, ip=10.42.0.182)   To:   2025-07
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) Processing Auction: 2024-08...
(PoolActor pid=671348, ip=10.42.0.182)   Filtered: 4 → 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) ================================================================================
(PoolActor pid=746008, ip=10.42.4.173) [Processing Auction Month: 2025-10]
(PoolActor pid=746008, ip=10.42.4.173)   Market Months: 1
(PoolActor pid=746008, ip=10.42.4.173)     - 2025-10
(PoolActor pid=746008, ip=10.42.4.173) ================================================================================
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) [STEP 1: Training Period Calculation]
(PoolActor pid=746008, ip=10.42.4.173)   Training Range: 2024-09 to 2025-09
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) [STEP 2: Loading Training Data]
(PoolActor pid=746008, ip=10.42.4.173)   Required period types: ['f0']
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) [Loading Training Data - Multi-Period Strategy]
(PoolActor pid=746008, ip=10.42.4.173) --------------------------------------------------------------------------------
(PoolActor pid=746008, ip=10.42.4.173)   Filtering to period types: ['f0']
(PoolActor pid=746008, ip=10.42.4.173) Training Window: 12 months
(PoolActor pid=746008, ip=10.42.4.173)   From: 2024-09
(PoolActor pid=746008, ip=10.42.4.173)   To:   2025-08
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2024-09...
(PoolActor pid=746008, ip=10.42.4.173)   Filtered: 3 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 11 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2024-08...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 4 → 1 period types
(PoolActor pid=746008, ip=10.42.4.173)   Loaded 10 samples across 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2024-10...
(PoolActor pid=746008, ip=10.42.4.173)   Filtered: 4 → 1 period types
(PoolActor pid=671348, ip=10.42.0.182)   Loaded 11 samples across 1 period types
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) Processing Auction: 2024-09...
(PoolActor pid=671348, ip=10.42.0.182)   Filtered: 3 → 1 period types
(PoolActor pid=907599, ip=10.42.6.149)   Loaded 11 samples across 1 period types
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) Processing Auction: 2024-06...
(PoolActor pid=730680, ip=10.42.9.131)   Loaded 10 samples across 1 period types
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) Processing Auction: 2024-07...
(PoolActor pid=730680, ip=10.42.9.131)   Filtered: 5 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 11 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2024-09...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 3 → 1 period types
(PoolActor pid=746008, ip=10.42.4.173)   Loaded 11 samples across 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2024-11...
(PoolActor pid=746008, ip=10.42.4.173)   Filtered: 4 → 1 period types
(PoolActor pid=730680, ip=10.42.9.131)   Loaded 11 samples across 1 period types
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) Processing Auction: 2024-08...
(PoolActor pid=730680, ip=10.42.9.131)   Filtered: 4 → 1 period types
(PoolActor pid=746008, ip=10.42.4.173)   Loaded 10 samples across 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2024-12...
(PoolActor pid=746008, ip=10.42.4.173)   Filtered: 3 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 10 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2024-10...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 4 → 1 period types
(PoolActor pid=730680, ip=10.42.9.131)   Loaded 11 samples across 1 period types
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) Processing Auction: 2024-09...
(PoolActor pid=730680, ip=10.42.9.131)   Filtered: 3 → 1 period types
(PoolActor pid=907599, ip=10.42.6.149)   Loaded 10 samples across 1 period types
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) Processing Auction: 2024-07...
(PoolActor pid=907599, ip=10.42.6.149)   Filtered: 5 → 1 period types
(PoolActor pid=671348, ip=10.42.0.182)   Loaded 10 samples across 1 period types
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) Processing Auction: 2024-10...
(PoolActor pid=671348, ip=10.42.0.182)   Filtered: 4 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 11 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2024-11...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 4 → 1 period types
(PoolActor pid=907599, ip=10.42.6.149)   Loaded 11 samples across 1 period types
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) Processing Auction: 2024-08...
(PoolActor pid=907599, ip=10.42.6.149)   Filtered: 4 → 1 period types
(PoolActor pid=671348, ip=10.42.0.182)   Loaded 11 samples across 1 period types
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) Processing Auction: 2024-11...
(PoolActor pid=671348, ip=10.42.0.182)   Filtered: 4 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 10 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2024-12...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 3 → 1 period types
(PoolActor pid=907599, ip=10.42.6.149)   Loaded 11 samples across 1 period types
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) Processing Auction: 2024-09...
(PoolActor pid=907599, ip=10.42.6.149)   Filtered: 3 → 1 period types
(PoolActor pid=671348, ip=10.42.0.182)   Loaded 10 samples across 1 period types
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) Processing Auction: 2024-12...
(PoolActor pid=671348, ip=10.42.0.182)   Filtered: 3 → 1 period types
(PoolActor pid=746008, ip=10.42.4.173)   Loaded 11 samples across 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2025-01...
(PoolActor pid=746008, ip=10.42.4.173)   Filtered: 3 → 1 period types
(PoolActor pid=730680, ip=10.42.9.131)   Loaded 10 samples across 1 period types
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) Processing Auction: 2024-10...
(PoolActor pid=730680, ip=10.42.9.131)   Filtered: 4 → 1 period types
(PoolActor pid=746008, ip=10.42.4.173)   Loaded 11 samples across 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2025-02...
(PoolActor pid=746008, ip=10.42.4.173)   Filtered: 4 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 11 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2025-01...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 3 → 1 period types
(PoolActor pid=730680, ip=10.42.9.131)   Loaded 11 samples across 1 period types
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) Processing Auction: 2024-11...
(PoolActor pid=730680, ip=10.42.9.131)   Filtered: 4 → 1 period types
(PoolActor pid=746008, ip=10.42.4.173)   Loaded 10 samples across 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2025-03...
(PoolActor pid=746008, ip=10.42.4.173)   Filtered: 3 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 11 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2025-02...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 4 → 1 period types
(PoolActor pid=907599, ip=10.42.6.149)   Loaded 10 samples across 1 period types
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) Processing Auction: 2024-10...
(PoolActor pid=907599, ip=10.42.6.149)   Filtered: 4 → 1 period types
(PoolActor pid=730680, ip=10.42.9.131)   Loaded 10 samples across 1 period types
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) Processing Auction: 2024-12...
(PoolActor pid=730680, ip=10.42.9.131)   Filtered: 3 → 1 period types
(PoolActor pid=671348, ip=10.42.0.182)   Loaded 11 samples across 1 period types
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) Processing Auction: 2025-01...
(PoolActor pid=671348, ip=10.42.0.182)   Filtered: 3 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 10 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2025-03...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 3 → 1 period types
(PoolActor pid=907599, ip=10.42.6.149)   Loaded 11 samples across 1 period types
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) Processing Auction: 2024-11...
(PoolActor pid=907599, ip=10.42.6.149)   Filtered: 4 → 1 period types
(PoolActor pid=671348, ip=10.42.0.182)   Loaded 11 samples across 1 period types
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) Processing Auction: 2025-02...
(PoolActor pid=671348, ip=10.42.0.182)   Filtered: 4 → 1 period types
(PoolActor pid=907599, ip=10.42.6.149)   Loaded 10 samples across 1 period types
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) Processing Auction: 2024-12...
(PoolActor pid=907599, ip=10.42.6.149)   Filtered: 3 → 1 period types
(PoolActor pid=671348, ip=10.42.0.182)   Loaded 10 samples across 1 period types
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) Processing Auction: 2025-03...
(PoolActor pid=671348, ip=10.42.0.182)   Filtered: 3 → 1 period types
(PoolActor pid=746008, ip=10.42.4.173)   Loaded 11 samples across 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2025-04...
(PoolActor pid=746008, ip=10.42.4.173)   Filtered: 2 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 11 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2025-04...
(PoolActor pid=732223, ip=10.42.8.15)   Filtered: 2 → 1 period types
(PoolActor pid=730680, ip=10.42.9.131)   Loaded 11 samples across 1 period types
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) Processing Auction: 2025-01...
(PoolActor pid=730680, ip=10.42.9.131)   Filtered: 3 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 10 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2025-05...
(PoolActor pid=746008, ip=10.42.4.173)   Loaded 10 samples across 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2025-05...
(PoolActor pid=730680, ip=10.42.9.131)   Loaded 11 samples across 1 period types
(PoolActor pid=730680, ip=10.42.9.131)
(PoolActor pid=730680, ip=10.42.9.131) Processing Auction: 2025-02...
(PoolActor pid=730680, ip=10.42.9.131)   Filtered: 4 → 1 period types
(PoolActor pid=732223, ip=10.42.8.15)   Loaded 11 samples across 1 period types
(PoolActor pid=732223, ip=10.42.8.15)
(PoolActor pid=732223, ip=10.42.8.15) Processing Auction: 2025-06...
(PoolActor pid=907599, ip=10.42.6.149)   Loaded 11 samples across 1 period types
(PoolActor pid=907599, ip=10.42.6.149)
(PoolActor pid=907599, ip=10.42.6.149) Processing Auction: 2025-01...
(PoolActor pid=907599, ip=10.42.6.149)   Filtered: 3 → 1 period types
(PoolActor pid=746008, ip=10.42.4.173)   Loaded 11 samples across 1 period types
(PoolActor pid=746008, ip=10.42.4.173)
(PoolActor pid=746008, ip=10.42.4.173) Processing Auction: 2025-06...
(PoolActor pid=671348, ip=10.42.0.182)   Loaded 11 samples across 1 period types
(PoolActor pid=671348, ip=10.42.0.182)
(PoolActor pid=671348, ip=10.42.0.182) Processing Auction: 2025-04...
(PoolActor pid=671348, ip=10.42.0.182)   Filtered: 2 → 1 period types

  0%|          | 0/6 [00:00<?, ?it/s]

================================================================================
[COMBINING RESULTS ACROSS ALL PERIODS]
================================================================================

✓ Results Combined
  Total samples (per-outage): 808,108
  Total unique constraints (monthly): 88,221
  Date range: 2025-06-01 to 2025-11-28

[ANALYZING COMBINED RESULTS]

================================================================================
[MONTHLY AGGREGATED RESULTS]
================================================================================

Test Period: Monthly Level
  Total samples: 88,221

[Shadow Price Prediction Performance]
  MAE:  $844.92
  RMSE: $78057.84
  MAPE: 3861.07%

[Classification Performance]
  Precision: 0.291
  Recall:    0.581
  F1-Score:  0.388
  Accuracy:  0.858

[Binding Classification Details]
  Correctly classified: 75,667 / 88,221 (85.77%)

  True Positives (correctly identified binding): 3,979
  False Positives (incorrectly predicted as binding): 9,682
  True Negatives (correctly identified non-binding): 71,688
  False Negatives (missed binding constraints): 2,872

[Binding Rate Analysis]
  Actual binding rate: 7.77% (6,851 samples)
  Predicted binding rate: 15.48% (13,661 samples)

================================================================================
[PER-OUTAGE SUMMARY]
================================================================================

Total outage dates: 63

Average metrics across outage dates:
  Avg F1-Score:  0.204
  Avg Precision: 0.141
  Avg Recall:    0.405
  Avg MAE:       $101.28

Per-Outage Performance:
  Date          Samples     F1   Prec    Rec        MAE
  ------------ -------- ------ ------ ------ ----------
  2025-06-01     12,722  0.262  0.184  0.460 $    66.20
  2025-06-04     12,774  0.104  0.060  0.387 $    63.17
  2025-06-07     12,816  0.241  0.157  0.513 $    53.93
  2025-06-10     12,809  0.262  0.186  0.446 $  1323.15
  2025-06-13     12,939  0.163  0.104  0.385 $  1325.31
  2025-06-16     12,822  0.190  0.125  0.395 $    50.15
  2025-06-19     12,846  0.217  0.142  0.462 $    54.57
  2025-06-22     12,815  0.136  0.078  0.517 $    59.69
  2025-06-25     12,810  0.204  0.131  0.460 $    62.01
  2025-06-28     12,888  0.180  0.111  0.466 $    40.54
  2025-07-01     12,852  0.207  0.134  0.454 $    59.11
  2025-07-04     12,933  0.077  0.043  0.398 $    46.50
  2025-07-07     12,834  0.215  0.142  0.435 $    62.09
  2025-07-10     12,851  0.191  0.119  0.494 $    54.36
  2025-07-13     12,836  0.192  0.129  0.377 $    70.27
  2025-07-16     12,841  0.184  0.120  0.401 $    58.35
  2025-07-19     12,918  0.215  0.134  0.542 $    52.71
  2025-07-22     12,893  0.209  0.136  0.445 $    64.13
  2025-07-25     12,908  0.131  0.074  0.570 $    43.85
  2025-07-28     12,919  0.222  0.148  0.445 $    65.21
  2025-07-31     12,909  0.071  0.040  0.295 $    43.85
  2025-08-01     12,977  0.166  0.106  0.376 $    40.58
  2025-08-04     12,921  0.202  0.137  0.385 $    47.10
  2025-08-07     12,933  0.219  0.144  0.457 $    55.80
  2025-08-10     12,842  0.249  0.166  0.498 $    51.31
  2025-08-13     12,865  0.251  0.174  0.450 $    63.27
  2025-08-16     12,912  0.114  0.072  0.267 $    58.33
  2025-08-19     12,896  0.225  0.161  0.370 $    69.86
  2025-08-22     12,919  0.151  0.104  0.278 $    43.31
  2025-08-25     12,900  0.188  0.136  0.306 $    53.42
  2025-08-28     12,927  0.138  0.085  0.376 $    43.59
  2025-08-31     12,921  0.000  0.000  0.000 $    47.49
  2025-09-01     12,885  0.325  0.266  0.418 $    59.55
  2025-09-04     12,952  0.298  0.242  0.390 $    53.58
  2025-09-07     12,829  0.354  0.287  0.463 $    59.89
  2025-09-10     12,781  0.333  0.261  0.458 $    56.94
  2025-09-13     12,792  0.217  0.140  0.472 $    63.65
  2025-09-16     12,731  0.217  0.143  0.448 $    67.81
  2025-09-19     12,789  0.136  0.078  0.507 $    52.68
  2025-09-22     12,643  0.222  0.144  0.485 $    66.99
  2025-09-25     12,709  0.218  0.140  0.495 $    54.61
  2025-09-28     12,741  0.220  0.144  0.463 $    62.91
  2025-10-01     12,646  0.281  0.202  0.465 $    93.07
  2025-10-04     12,691  0.165  0.102  0.431 $    74.87
  2025-10-07     12,642  0.281  0.211  0.419 $   103.63
  2025-10-10     12,743  0.231  0.156  0.443 $    68.74
  2025-10-13     12,621  0.279  0.210  0.416 $    93.98
  2025-10-16     12,729  0.252  0.187  0.384 $    84.83
  2025-10-19     12,767  0.291  0.233  0.388 $    87.96
  2025-10-22     12,751  0.241  0.171  0.408 $    66.66
  2025-10-25     12,787  0.273  0.200  0.432 $    64.49
  2025-10-28     12,765  0.304  0.240  0.412 $    72.11
  2025-10-31     12,795  0.213  0.134  0.513 $    50.02
  2025-11-01     12,778  0.284  0.200  0.494 $    59.78
  2025-11-04     12,666  0.321  0.257  0.427 $    85.41
  2025-11-07     12,837  0.247  0.190  0.351 $    60.27
  2025-11-10     12,712  0.202  0.152  0.303 $   100.26
  2025-11-13     12,732  0.223  0.148  0.452 $    64.65
  2025-11-16     12,797  0.250  0.164  0.525 $    67.74
  2025-11-19     12,792  0.174  0.105  0.513 $    63.68
  2025-11-22     13,005  0.000  0.000  0.000 $    44.75
  2025-11-25     13,004  0.000  0.000  0.000 $    43.34
  2025-11-28     13,048  0.000  0.000  0.000 $    38.62

================================================================================
✅ PIPELINE COMPLETE!
================================================================================

In [36]:
print(pipeline.config.features.step1_features) # For classifiers

['risk_ratio', 'curvature_100', 'prob_exceed_110', 'prob_exceed_105', 'prob_exceed_100', 'prob_exceed_95', 'prob_exceed_90', 'season_hist_da_1', 'season_hist_da_2', 'season_hist_da_3', 'recent_hist_da']

In [37]:
xgb_model = pipeline.trained_models[pd.Timestamp('2025-06-01')].clf_default_ensemble_f0[0][0]

# 2. Get feature names from config
# For classifiers, we use step1_features
feature_names = pipeline.config.features.step1_features

# 3. Create a DataFrame for readability
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': xgb_model.feature_importances_
}).sort_values('importance', ascending=False)

print(importance_df)

             feature  importance
6     prob_exceed_90    0.371392
10    recent_hist_da    0.101025
5     prob_exceed_95    0.068334
7   season_hist_da_1    0.062957
0         risk_ratio    0.062101
4    prob_exceed_100    0.061438
3    prob_exceed_105    0.061030
2    prob_exceed_110    0.059929
1      curvature_100    0.054334
9   season_hist_da_3    0.050763
8   season_hist_da_2    0.046697

In [16]:
# final_results.to_parquet('/opt/temp/haoyan/final_results_test.parquet')
# results_per_outage.to_parquet('/opt/temp/haoyan/results_per_outage_test.parquet')

In [38]:
metrics

{'monthly': {'mae': 844.9164626065061,
  'rmse': np.float64(78057.84285735543),
  'mape': np.float64(3861.074349830882),
  'precision': 0.29126711075323913,
  'recall': 0.5807911253831557,
  'f1_score': 0.3879680187207488,
  'accuracy': np.float64(0.857698280454767),
  'true_positives': 3979,
  'false_positives': 9682,
  'true_negatives': 71688,
  'false_negatives': 2872,
  'total_samples': 88221,
  'actual_binding_count': 6851,
  'predicted_binding_count': 13661,
  'actual_binding_rate': 0.07765724714070346,
  'predicted_binding_rate': 0.15484975232654358},
 'per_outage': {'2025-06-01': {'mae': 66.19675418322161,
   'rmse': np.float64(369.7572313874855),
   'mape': np.float64(163.1254644197319),
   'precision': 0.18361581920903955,
   'recall': 0.45990566037735847,
   'f1_score': 0.26244952893674295,
   'accuracy': np.float64(0.9138500235811979),
   'true_positives': 195,
   'false_positives': 867,
   'true_negatives': 11431,
   'false_negatives': 229,
   'total_samples': 12722,
   'actual_binding_count': 424,
   'predicted_binding_count': 1062,
   'actual_binding_rate': 0.03332809306712781,
   'predicted_binding_rate': 0.08347744065398523},
  '2025-06-04': {'mae': 63.16649064292936,
   'rmse': np.float64(417.4141823939466),
   'mape': np.float64(628.0956534295509),
   'precision': 0.06022944550669216,
   'recall': 0.38650306748466257,
   'f1_score': 0.10421836228287841,
   'accuracy': np.float64(0.9152184124001879),
   'true_positives': 63,
   'false_positives': 983,
   'true_negatives': 11628,
   'false_negatives': 100,
   'total_samples': 12774,
   'actual_binding_count': 163,
   'predicted_binding_count': 1046,
   'actual_binding_rate': 0.01276029434789416,
   'predicted_binding_rate': 0.08188507906685455},
  '2025-06-07': {'mae': 53.93291079085911,
   'rmse': np.float64(280.8654907189889),
   'mape': np.float64(541.1386224961518),
   'precision': 0.15717092337917485,
   'recall': 0.5128205128205128,
   'f1_score': 0.24060150375939848,
   'accuracy': np.float64(0.9211922596754057),
   'true_positives': 160,
   'false_positives': 858,
   'true_negatives': 11646,
   'false_negatives': 152,
   'total_samples': 12816,
   'actual_binding_count': 312,
   'predicted_binding_count': 1018,
   'actual_binding_rate': 0.024344569288389514,
   'predicted_binding_rate': 0.07943196004993758},
  '2025-06-10': {'mae': 1323.1489002126339,
   'rmse': np.float64(101085.20371746062),
   'mape': np.float64(941.496892973119),
   'precision': 0.18551587301587302,
   'recall': 0.44630071599045346,
   'f1_score': 0.2620882971268395,
   'accuracy': np.float64(0.917792177375283),
   'true_positives': 187,
   'false_positives': 821,
   'true_negatives': 11569,
   'false_negatives': 232,
   'total_samples': 12809,
   'actual_binding_count': 419,
   'predicted_binding_count': 1008,
   'actual_binding_rate': 0.0327113748145835,
   'predicted_binding_rate': 0.0786946678116949},
  '2025-06-13': {'mae': 1325.3126858645528,
   'rmse': np.float64(103169.63314653153),
   'mape': np.float64(2875.5567434558743),
   'precision': 0.10352187833511206,
   'recall': 0.38492063492063494,
   'f1_score': 0.1631623212783852,
   'accuracy': np.float64(0.9231007033001005),
   'true_positives': 97,
   'false_positives': 840,
   'true_negatives': 11847,
   'false_negatives': 155,
   'total_samples': 12939,
   'actual_binding_count': 252,
   'predicted_binding_count': 937,
   'actual_binding_rate': 0.01947600278228611,
   'predicted_binding_rate': 0.07241672463096066},
  '2025-06-16': {'mae': 50.14757394763343,
   'rmse': np.float64(282.51626977488235),
   'mape': np.float64(319.25871309399497),
   'precision': 0.12526096033402923,
   'recall': 0.39473684210526316,
   'f1_score': 0.1901743264659271,
   'accuracy': np.float64(0.920293245983466),
   'true_positives': 120,
   'false_positives': 838,
   'true_negatives': 11680,
   'false_negatives': 184,
   'total_samples': 12822,
   'actual_binding_count': 304,
   'predicted_binding_count': 958,
   'actual_binding_rate': 0.023709249727031666,
   'predicted_binding_rate': 0.07471533302136953},
  '2025-06-19': {'mae': 54.570139775622344,
   'rmse': np.float64(298.6495132089305),
   'mape': np.float64(352.7976163874309),
   'precision': 0.14208826695371368,
   'recall': 0.46153846153846156,
   'f1_score': 0.21728395061728395,
   'accuracy': np.float64(0.9259691732835124),
   'true_positives': 132,
   'false_positives': 797,
   'true_negatives': 11763,
   'false_negatives': 154,
   'total_samples': 12846,
   'actual_binding_count': 286,
   'predicted_binding_count': 929,
   'actual_binding_rate': 0.022263739685505216,
   'predicted_binding_rate': 0.07231823135606415},
  '2025-06-22': {'mae': 59.685991580222364,
   'rmse': np.float64(429.52091140779885),
   'mape': np.float64(181.42801234645933),
   'precision': 0.07802874743326489,
   'recall': 0.5170068027210885,
   'f1_score': 0.13559322033898305,
   'accuracy': np.float64(0.9243854857588764),
   'true_positives': 76,
   'false_positives': 898,
   'true_negatives': 11770,
   'false_negatives': 71,
   'total_samples': 12815,
   'actual_binding_count': 147,
   'predicted_binding_count': 974,
   'actual_binding_rate': 0.011470932500975419,
   'predicted_binding_rate': 0.0760046820132657},
  '2025-06-25': {'mae': 62.00587254548712,
   'rmse': np.float64(410.69257594936636),
   'mape': np.float64(645.1013588634894),
   'precision': 0.13108242303872888,
   'recall': 0.45993031358885017,
   'f1_score': 0.20401854714064915,
   'accuracy': np.float64(0.9195940671350508),
   'true_positives': 132,
   'false_positives': 875,
   'true_negatives': 11648,
   'false_negatives': 155,
   'total_samples': 12810,
   'actual_binding_count': 287,
   'predicted_binding_count': 1007,
   'actual_binding_rate': 0.022404371584699455,
   'predicted_binding_rate': 0.0786104605776737},
  '2025-06-28': {'mae': 40.53629499647214,
   'rmse': np.float64(235.3881809159055),
   'mape': np.float64(386.01427183140163),
   'precision': 0.11147186147186147,
   'recall': 0.4660633484162896,
   'f1_score': 0.1799126637554585,
   'accuracy': np.float64(0.9271415270018621),
   'true_positives': 103,
   'false_positives': 821,
   'true_negatives': 11846,
   'false_negatives': 118,
   'total_samples': 12888,
   'actual_binding_count': 221,
   'predicted_binding_count': 924,
   'actual_binding_rate': 0.017147734326505275,
   'predicted_binding_rate': 0.07169459962756052},
  '2025-07-01': {'mae': 59.11360394768429,
   'rmse': np.float64(327.09246224440284),
   'mape': np.float64(223.1356172455138),
   'precision': 0.1342031686859273,
   'recall': 0.45425867507886436,
   'f1_score': 0.20719424460431654,
   'accuracy': np.float64(0.914254590725179),
   'true_positives': 144,
   'false_positives': 929,
   'true_negatives': 11606,
   'false_negatives': 173,
   'total_samples': 12852,
   'actual_binding_count': 317,
   'predicted_binding_count': 1073,
   'actual_binding_rate': 0.024665421724245254,
   'predicted_binding_rate': 0.08348895113600996},
  '2025-07-04': {'mae': 46.49691657284937,
   'rmse': np.float64(285.17475677709956),
   'mape': np.float64(476.7270991488867),
   'precision': 0.04257425742574258,
   'recall': 0.39814814814814814,
   'f1_score': 0.07692307692307693,
   'accuracy': np.float64(0.9202041289723962),
   'true_positives': 43,
   'false_positives': 967,
   'true_negatives': 11858,
   'false_negatives': 65,
   'total_samples': 12933,
   'actual_binding_count': 108,
   'predicted_binding_count': 1010,
   'actual_binding_rate': 0.008350730688935281,
   'predicted_binding_rate': 0.0780947962576355},
  '2025-07-07': {'mae': 62.08923081321473,
   'rmse': np.float64(354.65378505013103),
   'mape': np.float64(243.58576242593423),
   'precision': 0.1424390243902439,
   'recall': 0.43452380952380953,
   'f1_score': 0.2145481263776635,
   'accuracy': np.float64(0.9167056256817827),
   'true_positives': 146,
   'false_positives': 879,
   'true_negatives': 11619,
   'false_negatives': 190,
   'total_samples': 12834,
   'actual_binding_count': 336,
   'predicted_binding_count': 1025,
   'actual_binding_rate': 0.026180458158017766,
   'predicted_binding_rate': 0.07986598098800063},
  '2025-07-10': {'mae': 54.358285345173464,
   'rmse': np.float64(266.06499084367675),
   'mape': np.float64(244.38308247494106),
   'precision': 0.11870503597122302,
   'recall': 0.4943820224719101,
   'f1_score': 0.19144307469180566,
   'accuracy': np.float64(0.9132363240214769),
   'true_positives': 132,
   'false_positives': 980,
   'true_negatives': 11604,
   'false_negatives': 135,
   'total_samples': 12851,
   'actual_binding_count': 267,
   'predicted_binding_count': 1112,
   'actual_binding_rate': 0.02077659326122481,
   'predicted_binding_rate': 0.08653023111041942},
  '2025-07-13': {'mae': 70.27337766243089,
   'rmse': np.float64(382.2335469362538),
   'mape': np.float64(212.25791763596112),
   'precision': 0.12880143112701253,
   'recall': 0.3769633507853403,
   'f1_score': 0.192,
   'accuracy': np.float64(0.9055780617014646),
   'true_positives': 144,
   'false_positives': 974,
   'true_negatives': 11480,
   'false_negatives': 238,
   'total_samples': 12836,
   'actual_binding_count': 382,
   'predicted_binding_count': 1118,
   'actual_binding_rate': 0.029760049859769398,
   'predicted_binding_rate': 0.0870987846681209},
  '2025-07-16': {'mae': 58.35096869757516,
   'rmse': np.float64(298.3047335568885),
   'mape': np.float64(2028.3530935919596),
   'precision': 0.11967361740707162,
   'recall': 0.4012158054711246,
   'f1_score': 0.18435754189944134,
   'accuracy': np.float64(0.9090413519196324),
   'true_positives': 132,
   'false_positives': 971,
   'true_negatives': 11541,
   'false_negatives': 197,
   'total_samples': 12841,
   'actual_binding_count': 329,
   'predicted_binding_count': 1103,
   'actual_binding_rate': 0.025621057550035044,
   'predicted_binding_rate': 0.08589673701425123},
  '2025-07-19': {'mae': 52.705186881094384,
   'rmse': np.float64(288.6855192139433),
   'mape': np.float64(176.95876553610586),
   'precision': 0.1337890625,
   'recall': 0.541501976284585,
   'f1_score': 0.21456538762725136,
   'accuracy': np.float64(0.9223564019198018),
   'true_positives': 137,
   'false_positives': 887,
   'true_negatives': 11778,
   'false_negatives': 116,
   'total_samples': 12918,
   'actual_binding_count': 253,
   'predicted_binding_count': 1024,
   'actual_binding_rate': 0.019585075089023067,
   'predicted_binding_rate': 0.07926923672395107},
  '2025-07-22': {'mae': 64.13001253149942,
   'rmse': np.float64(420.6457993469462),
   'mape': np.float64(305.87292610870185),
   'precision': 0.13649851632047477,
   'recall': 0.44516129032258067,
   'f1_score': 0.20893262679788038,
   'accuracy': np.float64(0.9189482665012022),
   'true_positives': 138,
   'false_positives': 873,
   'true_negatives': 11710,
   'false_negatives': 172,
   'total_samples': 12893,
   'actual_binding_count': 310,
   'predicted_binding_count': 1011,
   'actual_binding_rate': 0.024044054913518964,
   'predicted_binding_rate': 0.07841464360505701},
  '2025-07-25': {'mae': 43.84845986079585,
   'rmse': np.float64(235.86585817856448),
   'mape': np.float64(154.23423147254786),
   'precision': 0.07426246185147507,
   'recall': 0.5703125,
   'f1_score': 0.13141314131413143,
   'accuracy': np.float64(0.9252401611403781),
   'true_positives': 73,
   'false_positives': 910,
   'true_negatives': 11870,
   'false_negatives': 55,
   'total_samples': 12908,
   'actual_binding_count': 128,
   'predicted_binding_count': 983,
   'actual_binding_rate': 0.009916330957545709,
   'predicted_binding_rate': 0.0761543229005268},
  '2025-07-28': {'mae': 65.21337878703181,
   'rmse': np.float64(392.65913460431665),
   'mape': np.float64(2214.970030003627),
   'precision': 0.14807302231237324,
   'recall': 0.4451219512195122,
   'f1_score': 0.2222222222222222,
   'accuracy': np.float64(0.920891709884666),
   'true_positives': 146,
   'false_positives': 840,
   'true_negatives': 11751,
   'false_negatives': 182,
   'total_samples': 12919,
   'actual_binding_count': 328,
   'predicted_binding_count': 986,
   'actual_binding_rate': 0.025388961993962383,
   'predicted_binding_rate': 0.07632169672575277},
  '2025-07-31': {'mae': 43.85222444195651,
   'rmse': np.float64(259.95487643544993),
   'mape': np.float64(4921.351137082111),
   'precision': 0.040382571732199786,
   'recall': 0.29457364341085274,
   'f1_score': 0.07102803738317758,
   'accuracy': np.float64(0.9229994577426601),
   'true_positives': 38,
   'false_positives': 903,
   'true_negatives': 11877,
   'false_negatives': 91,
   'total_samples': 12909,
   'actual_binding_count': 129,
   'predicted_binding_count': 941,
   'actual_binding_rate': 0.009993028119916338,
   'predicted_binding_rate': 0.07289487954140522},
  '2025-08-01': {'mae': 40.58118227446622,
   'rmse': np.float64(239.9913846860532),
   'mape': np.float64(246.93328404844763),
   'precision': 0.10607734806629834,
   'recall': 0.3764705882352941,
   'f1_score': 0.16551724137931034,
   'accuracy': np.float64(0.9254064884025583),
   'true_positives': 96,
   'false_positives': 809,
   'true_negatives': 11913,
   'false_negatives': 159,
   'total_samples': 12977,
   'actual_binding_count': 255,
   'predicted_binding_count': 905,
   'actual_binding_rate': 0.019650150265854975,
   'predicted_binding_rate': 0.06973876859058334},
  '2025-08-04': {'mae': 47.09673358206902,
   'rmse': np.float64(278.70632950072047),
   'mape': np.float64(179.39379571097868),
   'precision': 0.13732004429678848,
   'recall': 0.38509316770186336,
   'f1_score': 0.20244897959183675,
   'accuracy': np.float64(0.9243866573794598),
   'true_positives': 124,
   'false_positives': 779,
   'true_negatives': 11820,
   'false_negatives': 198,
   'total_samples': 12921,
   'actual_binding_count': 322,
   'predicted_binding_count': 903,
   'actual_binding_rate': 0.024920671774630445,
   'predicted_binding_rate': 0.06988623171581147},
  '2025-08-07': {'mae': 55.800300559968804,
   'rmse': np.float64(396.86941778972033),
   'mape': np.float64(4490.098930358672),
   'precision': 0.14382022471910114,
   'recall': 0.45714285714285713,
   'f1_score': 0.2188034188034188,
   'accuracy': np.float64(0.9293280754658625),
   'true_positives': 128,
   'false_positives': 762,
   'true_negatives': 11891,
   'false_negatives': 152,
   'total_samples': 12933,
   'actual_binding_count': 280,
   'predicted_binding_count': 890,
   'actual_binding_rate': 0.02165004252686925,
   'predicted_binding_rate': 0.06881620660326297},
  '2025-08-10': {'mae': 51.31301376009671,
   'rmse': np.float64(310.2480471803701),
   'mape': np.float64(1307.7091414330046),
   'precision': 0.16611661166116612,
   'recall': 0.49834983498349833,
   'f1_score': 0.24917491749174916,
   'accuracy': np.float64(0.9291387634324871),
   'true_positives': 151,
   'false_positives': 758,
   'true_negatives': 11781,
   'false_negatives': 152,
   'total_samples': 12842,
   'actual_binding_count': 303,
   'predicted_binding_count': 909,
   'actual_binding_rate': 0.023594455692259774,
   'predicted_binding_rate': 0.07078336707677932},
  '2025-08-13': {'mae': 63.27160775120454,
   'rmse': np.float64(414.0426714246807),
   'mape': np.float64(367.28197312366626),
   'precision': 0.17444444444444446,
   'recall': 0.4498567335243553,
   'f1_score': 0.2514011208967174,
   'accuracy': np.float64(0.9273221919937816),
   'true_positives': 157,
   'false_positives': 743,
   'true_negatives': 11773,
   'false_negatives': 192,
   'total_samples': 12865,
   'actual_binding_count': 349,
   'predicted_binding_count': 900,
   'actual_binding_rate': 0.02712786630392538,
   'predicted_binding_rate': 0.06995724834823164},
  '2025-08-16': {'mae': 58.33110616269994,
   'rmse': np.float64(409.57812742865644),
   'mape': np.float64(511.2161833494108),
   'precision': 0.07222222222222222,
   'recall': 0.2674897119341564,
   'f1_score': 0.1137357830271216,
   'accuracy': np.float64(0.9215458488228006),
   'true_positives': 65,
   'false_positives': 835,
   'true_negatives': 11834,
   'false_negatives': 178,
   'total_samples': 12912,
   'actual_binding_count': 243,
   'predicted_binding_count': 900,
   'actual_binding_rate': 0.018819702602230485,
   'predicted_binding_rate': 0.06970260223048327},
  '2025-08-19': {'mae': 69.86311769000262,
   'rmse': np.float64(499.0869798741897),
   'mape': np.float64(298.33782165474736),
   'precision': 0.16114285714285714,
   'recall': 0.3700787401574803,
   'f1_score': 0.22452229299363058,
   'accuracy': np.float64(0.9244727047146402),
   'true_positives': 141,
   'false_positives': 734,
   'true_negatives': 11781,
   'false_negatives': 240,
   'total_samples': 12896,
   'actual_binding_count': 381,
   'predicted_binding_count': 875,
   'actual_binding_rate': 0.029544044665012408,
   'predicted_binding_rate': 0.06785049627791563},
  '2025-08-22': {'mae': 43.30765647886319,
   'rmse': np.float64(267.2876713926317),
   'mape': np.float64(162.36940242449433),
   'precision': 0.10356347438752785,
   'recall': 0.27761194029850744,
   'f1_score': 0.15085158150851583,
   'accuracy': np.float64(0.9189565755863457),
   'true_positives': 93,
   'false_positives': 805,
   'true_negatives': 11779,
   'false_negatives': 242,
   'total_samples': 12919,
   'actual_binding_count': 335,
   'predicted_binding_count': 898,
   'actual_binding_rate': 0.025930799597492067,
   'predicted_binding_rate': 0.0695100239956653},
  '2025-08-25': {'mae': 53.42078088778359,
   'rmse': np.float64(357.5671806503455),
   'mape': np.float64(472.7533077522245),
   'precision': 0.1361079865016873,
   'recall': 0.30632911392405066,
   'f1_score': 0.18847352024922118,
   'accuracy': np.float64(0.9192248062015503),
   'true_positives': 121,
   'false_positives': 768,
   'true_negatives': 11737,
   'false_negatives': 274,
   'total_samples': 12900,
   'actual_binding_count': 395,
   'predicted_binding_count': 889,
   'actual_binding_rate': 0.03062015503875969,
   'predicted_binding_rate': 0.06891472868217054},
  '2025-08-28': {'mae': 43.59430754119581,
   'rmse': np.float64(282.16545412670354),
   'mape': np.float64(1105.9789027076276),
   'precision': 0.08458244111349036,
   'recall': 0.3761904761904762,
   'f1_score': 0.1381118881118881,
   'accuracy': np.float64(0.9237255357004719),
   'true_positives': 79,
   'false_positives': 855,
   'true_negatives': 11862,
   'false_negatives': 131,
   'total_samples': 12927,
   'actual_binding_count': 210,
   'predicted_binding_count': 934,
   'actual_binding_rate': 0.016245068461359945,
   'predicted_binding_rate': 0.07225187591861994},
  '2025-08-31': {'mae': 47.49075189765859,
   'rmse': np.float64(262.8162100573146),
   'mape': 0.0,
   'precision': 0.0,
   'recall': 0.0,
   'f1_score': 0.0,
   'accuracy': np.float64(0.9170342852720378),
   'true_positives': 0,
   'false_positives': 1072,
   'true_negatives': 11849,
   'false_negatives': 0,
   'total_samples': 12921,
   'actual_binding_count': 0,
   'predicted_binding_count': 1072,
   'actual_binding_rate': 0.0,
   'predicted_binding_rate': 0.08296571472796223},
  '2025-09-01': {'mae': 59.54665117526248,
   'rmse': np.float64(373.9522010920846),
   'mape': np.float64(2269.3304277258753),
   'precision': 0.2658092175777063,
   'recall': 0.4175084175084175,
   'f1_score': 0.32481990831696134,
   'accuracy': np.float64(0.9199844780752814),
   'true_positives': 248,
   'false_positives': 685,
   'true_negatives': 11606,
   'false_negatives': 346,
   'total_samples': 12885,
   'actual_binding_count': 594,
   'predicted_binding_count': 933,
   'actual_binding_rate': 0.04610011641443539,
   'predicted_binding_rate': 0.07240977881257275},
  '2025-09-04': {'mae': 53.58235117870195,
   'rmse': np.float64(296.16183277614056),
   'mape': np.float64(1639.241308364928),
   'precision': 0.24171122994652405,
   'recall': 0.3896551724137931,
   'f1_score': 0.2983498349834984,
   'accuracy': np.float64(0.9179277331686226),
   'true_positives': 226,
   'false_positives': 709,

In [39]:
sig_list = []
for date in pd.date_range('2025-06', '2025-11', freq='MS'):
    # if date.month in [5, 6]:
    #     continue
    date_str = date.strftime('%Y-%m')
    f1_sig = pd.read_parquet(f'/opt/data/xyz-dataset/signal_data/miso/constraints/TEST.TEST.Signal.MISO.SPICE_F0P_V6.2B.R1/{date_str}/f0/onpeak/')
    f1_sig['auction_month'] = date
    sig_list.append(f1_sig)

sig_df = pd.concat(sig_list)
sig_df.sort_values('tier', ascending=True).drop_duplicates(subset=['auction_month', 'branch_name'], keep='first')

fin_df = final_results.sort_values(['binding_probability_scaled'], ascending=False).drop_duplicates(subset=['auction_month', 'branch_name'], keep='first')

In [40]:
df = fin_df.reset_index().merge(sig_df, on=['branch_name', 'auction_month'], how='outer')
df = df[~df['constraint_id_x'].isin(['SO_MW_Transfer'])]

In [41]:
print(df[(df['actual_shadow_price'] > 1000) & (df['tier'].isna()) & (df['predicted_binding_count'] >= 2)].sort_values('actual_shadow_price').shape)
print(df[(df['actual_shadow_price'] > 1000) & (df['tier'].notna()) & (df['predicted_binding_count'] == 0)].sort_values('actual_shadow_price').shape)
print(df[(df['actual_shadow_price'] > 1000) & (df['tier'].notna()) & (df['predicted_binding_count'] >= 2)].sort_values('actual_shadow_price').shape)
print(df[(df['actual_shadow_price'] > 1000) & (df['predicted_binding_count'] >= 2)].sort_values('actual_shadow_price').shape)
print(df[(df['actual_shadow_price'] > 1000) & (df['tier'].notna())].sort_values('actual_shadow_price').shape)

(61, 46)
(56, 46)
(283, 46)
(344, 46)
(376, 46)

In [42]:
df['sig_pred'] = (df['actual_shadow_price'] > 1000) & (df['tier'] <= 4)
df['sig_has_pred'] = df['tier'] <= 4
ddf = df.groupby('auction_month')[['sig_pred', 'sig_has_pred']].sum()
ddf['sig_pred_rate'] = ddf['sig_pred'] / ddf['sig_has_pred']
ddf.describe()

        sig_pred  sig_has_pred  sig_pred_rate
count   6.000000      6.000000       6.000000
mean   62.666667    585.166667       0.107469
std    17.362795    104.935059       0.021654
min    49.000000    488.000000       0.078404
25%    54.000000    496.500000       0.099230
50%    58.000000    559.000000       0.102254
75%    60.500000    666.500000       0.116966
max    97.000000    727.000000       0.141813

In [43]:
df['sig_pred'] = (df['actual_shadow_price'] > 1000) & (df['predicted_binding_count'] >= 2)
df['sig_has_pred'] = df['predicted_binding_count'] >= 2
df.groupby('auction_month')[['sig_pred', 'sig_has_pred']].sum()
ddf = df.groupby('auction_month')[['sig_pred', 'sig_has_pred']].sum()
ddf['sig_pred_rate'] = ddf['sig_pred'] / ddf['sig_has_pred']
ddf.describe()

        sig_pred  sig_has_pred  sig_pred_rate
count   6.000000      6.000000       6.000000
mean   57.333333    569.333333       0.100603
std    14.348054     85.787334       0.016352
min    47.000000    451.000000       0.076923
25%    51.000000    531.250000       0.095117
50%    52.000000    550.000000       0.101013
75%    55.250000    635.500000       0.103476
max    86.000000    676.000000       0.127219

In [ ]:
metrics

{'monthly': {'mae': 473.9555450442503,
  'rmse': np.float64(3366.3656046556816),
  'mape': np.float64(29498.3000746118),
  'precision': 0.2899688554373216,
  'recall': 0.27880716201884087,
  'f1_score': 0.28427848986991505,
  'accuracy': np.float64(0.8877846150777424),
  'true_positives': 4469,
  'false_positives': 10943,
  'true_negatives': 173562,
  'false_negatives': 11560,
  'total_samples': 200534,
  'actual_binding_count': 16029,
  'predicted_binding_count': 15412,
  'actual_binding_rate': 0.07993158267425973,
  'predicted_binding_rate': 0.07685479769016726},
 'per_outage': {'2024-08-01': {'mae': 43.83626895834911,
   'rmse': np.float64(329.51001796580954),
   'mape': np.float64(159.53908680118045),
   'precision': 0.14717741935483872,
   'recall': 0.26838235294117646,
   'f1_score': 0.19010416666666666,
   'accuracy': np.float64(0.9510621557828481),
   'true_positives': 73,
   'false_positives': 423,
   'true_negatives': 12015,
   'false_negatives': 199,
   'total_samples': 12710,
   'actual_binding_count': 272,
   'predicted_binding_count': 496,
   'actual_binding_rate': 0.02140047206923682,
   'predicted_binding_rate': 0.03902439024390244},
  '2024-08-04': {'mae': 50.88492299795844,
   'rmse': np.float64(333.65318257552656),
   'mape': np.float64(438.975030119638),
   'precision': 0.14849624060150377,
   'recall': 0.20789473684210527,
   'f1_score': 0.17324561403508773,
   'accuracy': np.float64(0.9407837901515747),
   'true_positives': 79,
   'false_positives': 453,
   'true_negatives': 11900,
   'false_negatives': 301,
   'total_samples': 12733,
   'actual_binding_count': 380,
   'predicted_binding_count': 532,
   'actual_binding_rate': 0.029843713186209063,
   'predicted_binding_rate': 0.04178119846069269},
  '2024-08-07': {'mae': 43.64985161166002,
   'rmse': np.float64(305.14546318767617),
   'mape': np.float64(1010.8725172926391),
   'precision': 0.14549180327868852,
   'recall': 0.23355263157894737,
   'f1_score': 0.17929292929292928,
   'accuracy': np.float64(0.9488873161909255),
   'true_positives': 71,
   'false_positives': 417,
   'true_negatives': 11996,
   'false_negatives': 233,
   'total_samples': 12717,
   'actual_binding_count': 304,
   'predicted_binding_count': 488,
   'actual_binding_rate': 0.02390500904301329,
   'predicted_binding_rate': 0.038373830305889756},
  '2024-08-10': {'mae': 43.316512315929664,
   'rmse': np.float64(306.4434845839038),
   'mape': np.float64(1322.755421775334),
   'precision': 0.08185053380782918,
   'recall': 0.24864864864864866,
   'f1_score': 0.12315930388219545,
   'accuracy': np.float64(0.9484048838125246),
   'true_positives': 46,
   'false_positives': 516,
   'true_negatives': 11994,
   'false_negatives': 139,
   'total_samples': 12695,
   'actual_binding_count': 185,
   'predicted_binding_count': 562,
   'actual_binding_rate': 0.0145726664040961,
   'predicted_binding_rate': 0.0442693974005514},
  '2024-08-13': {'mae': 54.60019123021586,
   'rmse': np.float64(350.7283544417204),
   'mape': np.float64(126.93696865683582),
   'precision': 0.22426470588235295,
   'recall': 0.2646420824295011,
   'f1_score': 0.2427860696517413,
   'accuracy': np.float64(0.9401447223533113),
   'true_positives': 122,
   'false_positives': 422,
   'true_negatives': 11831,
   'false_negatives': 339,
   'total_samples': 12714,
   'actual_binding_count': 461,
   'predicted_binding_count': 544,
   'actual_binding_rate': 0.03625924178071417,
   'predicted_binding_rate': 0.042787478370300454},
  '2024-08-16': {'mae': 39.699281192399695,
   'rmse': np.float64(267.4333764637465),
   'mape': np.float64(190.5618107798231),
   'precision': 0.20037453183520598,
   'recall': 0.3119533527696793,
   'f1_score': 0.24401368301026224,
   'accuracy': np.float64(0.9478527607361963),
   'true_positives': 107,
   'false_positives': 427,
   'true_negatives': 11944,
   'false_negatives': 236,
   'total_samples': 12714,
   'actual_binding_count': 343,
   'predicted_binding_count': 534,
   'actual_binding_rate': 0.02697813434009753,
   'predicted_binding_rate': 0.042000943841434636},
  '2024-08-19': {'mae': 47.64581158581425,
   'rmse': np.float64(330.54339820632106),
   'mape': np.float64(23343.355750690007),
   'precision': 0.18908382066276802,
   'recall': 0.24556962025316456,
   'f1_score': 0.21365638766519823,
   'accuracy': np.float64(0.9438237608182534),
   'true_positives': 97,
   'false_positives': 416,
   'true_negatives': 11899,
   'false_negatives': 298,
   'total_samples': 12710,
   'actual_binding_count': 395,
   'predicted_binding_count': 513,
   'actual_binding_rate': 0.03107789142407553,
   'predicted_binding_rate': 0.04036191974822974},
  '2024-08-22': {'mae': 41.58837293505828,
   'rmse': np.float64(296.2003730246243),
   'mape': np.float64(7578.392400117736),
   'precision': 0.1494949494949495,
   'recall': 0.26148409893992935,
   'f1_score': 0.19023136246786632,
   'accuracy': np.float64(0.9504755915415455),
   'true_positives': 74,
   'false_positives': 421,
   'true_negatives': 12017,
   'false_negatives': 209,
   'total_samples': 12721,
   'actual_binding_count': 283,
   'predicted_binding_count': 495,
   'actual_binding_rate': 0.022246678720226398,
   'predicted_binding_rate': 0.03891203521735712},
  '2024-08-25': {'mae': 53.07815169812749,
   'rmse': np.float64(348.49339660056484),
   'mape': np.float64(278.1426382074625),
   'precision': 0.13346228239845262,
   'recall': 0.23875432525951557,
   'f1_score': 0.17121588089330025,
   'accuracy': np.float64(0.94745122718691),
   'true_positives': 69,
   'false_positives': 448,
   'true_negatives': 11975,
   'false_negatives': 220,
   'total_samples': 12712,
   'actual_binding_count': 289,
   'predicted_binding_count': 517,
   'actual_binding_rate': 0.022734424166142228,
   'predicted_binding_rate': 0.04067023285084959},
  '2024-08-28': {'mae': 64.58960491273352,
   'rmse': np.float64(456.0329068676794),
   'mape': np.float64(1617.334708896029),
   'precision': 0.15728155339805824,
   'recall': 0.2403560830860534,
   'f1_score': 0.19014084507042253,
   'accuracy': np.float64(0.9457760314341846),
   'true_positives': 81,
   'false_positives': 434,
   'true_negatives': 11954,
   'false_negatives': 256,
   'total_samples': 12725,
   'actual_binding_count': 337,
   'predicted_binding_count': 515,
   'actual_binding_rate': 0.026483300589390964,
   'predicted_binding_rate': 0.040471512770137524},
  '2024-08-31': {'mae': 37.96739489871758,
   'rmse': np.float64(324.8528888115394),
   'mape': 0.0,
   'precision': 0.0,
   'recall': 0.0,
   'f1_score': 0.0,
   'accuracy': np.float64(0.9595461658841941),
   'true_positives': 0,
   'false_positives': 517,
   'true_negatives': 12263,
   'false_negatives': 0,
   'total_samples': 12780,
   'actual_binding_count': 0,
   'predicted_binding_count': 517,
   'actual_binding_rate': 0.0,
   'predicted_binding_rate': 0.04045383411580595},
  '2024-09-01': {'mae': 49.68919947698052,
   'rmse': np.float64(383.20903605778113),
   'mape': np.float64(732.4787862477749),
   'precision': 0.20281124497991967,
   'recall': 0.30606060606060603,
   'f1_score': 0.24396135265700483,
   'accuracy': np.float64(0.9506387005204227),
   'true_positives': 101,
   'false_positives': 397,
   'true_negatives': 11955,
   'false_negatives': 229,
   'total_samples': 12682,
   'actual_binding_count': 330,
   'predicted_binding_count': 498,
   'actual_binding_rate': 0.02602113231351522,
   'predicted_binding_rate': 0.03926825421857751},
  '2024-09-04': {'mae': 50.349971132021096,
   'rmse': np.float64(386.28335729992915),
   'mape': np.float64(465.09975413746105),
   'precision': 0.18533604887983707,
   'recall': 0.2388451443569554,
   'f1_score': 0.20871559633027523,
   'accuracy': np.float64(0.9452380952380952),
   'true_positives': 91,
   'false_positives': 400,
   'true_negatives': 11819,
   'false_negatives': 290,
   'total_samples': 12600,
   'actual_binding_count': 381,
   'predicted_binding_count': 491,
   'actual_binding_rate': 0.030238095238095238,
   'predicted_binding_rate': 0.03896825396825397},
  '2024-09-07': {'mae': 52.39601896756722,
   'rmse': np.float64(377.37172783878486),
   'mape': np.float64(9188.996542808689),
   'precision': 0.12927756653992395,
   'recall': 0.16152019002375298,
   'f1_score': 0.14361140443505807,
   'accuracy': np.float64(0.9352908322029841),
   'true_positives': 68,
   'false_positives': 458,
   'true_negatives': 11654,
   'false_negatives': 353,
   'total_samples': 12533,
   'actual_binding_count': 421,
   'predicted_binding_count': 526,
   'actual_binding_rate': 0.033591318918056334,
   'predicted_binding_rate': 0.04196920130854544},
  '2024-09-10': {'mae': 66.57496577000605,
   'rmse': np.float64(484.8019359875266),
   'mape': np.float64(250.0606487398985),
   'precision': 0.19286871961102106,
   'recall': 0.2361111111111111,
   'f1_score': 0.21231043710972347,
   'accuracy': np.float64(0.9292637987663221),
   'true_positives': 119,
   'false_positives': 498,
   'true_negatives': 11481,
   'false_negatives': 385,
   'total_samples': 12483,
   'actual_binding_count': 504,
   'predicted_binding_count': 617,
   'actual_binding_rate': 0.04037490987743331,
   'predicted_binding_rate': 0.049427221020588},
  '2024-09-13': {'mae': 50.393553064090824,
   'rmse': np.float64(401.44872156178025),
   'mape': np.float64(471.18299036354665),
   'precision': 0.19140625,
   'recall': 0.2474747474747475,
   'f1_score': 0.21585903083700442,
   'accuracy': np.float64(0.9432624113475178),
   'true_positives': 98,
   'false_positives': 414,
   'true_negatives': 11739,
   'false_negatives': 298,
   'total_samples': 12549,
   'actual_binding_count': 396,
   'predicted_binding_count': 512,
   'actual_binding_rate': 0.03155629930671767,
   'predicted_binding_rate': 0.04080006375009961},
  '2024-09-16': {'mae': 89.00078697398779,
   'rmse': np.float64(713.1797095780981),
   'mape': np.float64(356.90067277646716),
   'precision': 0.2421602787456446,
   'recall': 0.2627599243856333,
   'f1_score': 0.25203989120580234,
   'accuracy': np.float64(0.933338720103426),
   'true_positives': 139,
   'false_positives': 435,
   'true_negatives': 11412,
   'false_negatives': 390,
   'total_samples': 12376,
   'actual_binding_count': 529,
   'predicted_binding_count': 574,
   'actual_binding_rate': 0.04274402068519716,
   'predicted_binding_rate': 0.04638009049773756},
  '2024-09-19': {'mae': 50.20029980450665,
   'rmse': np.float64(366.0967866132891),
   'mape': np.float64(861.2710829671663),
   'precision': 0.13893653516295026,
   'recall': 0.226890756302521,
   'f1_score': 0.1723404255319149,
   'accuracy': np.float64(0.9374849337083166),
   'true_positives': 81,
   'false_positives': 502,
   'true_negatives': 11586,
   'false_negatives': 276,
   'total_samples': 12445,
   'actual_binding_count': 357,
   'predicted_binding_count': 583,
   'actual_binding_rate': 0.02868621936520691,
   'predicted_binding_rate': 0.046846122940940135},
  '2024-09-22': {'mae': 51.172185187153346,
   'rmse': np.float64(364.5065513556504),
   'mape': np.float64(148.39244265533452),
   'precision': 0.16998468606431852,
   'recall': 0.3523809523809524,
   'f1_score': 0.22933884297520662,
   'accuracy': np.float64(0.9403534020948269),
   'true_positives': 111,
   'false_positives': 542,
   'true_negatives': 11650,
   'false_negatives': 204,
   'total_samples': 12507,
   'actual_binding_count': 315,
   'predicted_binding_count': 653,
   'actual_binding_rate': 0.025185895898296954,
   'predicted_binding_rate': 0.05221076197329495},
  '2024-09-25': {'mae': 61.78117656497937,
   'rmse': np.float64(407.68052202020914),
   'mape': np.float64(481.0666641817831),
   'precision': 0.17052023121387283,
   'recall': 0.271264367816092,
   'f1_score': 0.20940550133096716,
   'accuracy': np.float64(0.9287655900223857),
   'true_positives': 118,
   'false_positives': 574,
   'true_negatives': 11499,
   'false_negatives': 317,
   'total_samples': 12508,
   'actual_binding_count': 435,
   'predicted_binding_count': 692,
   'actual_binding_rate': 0.034777742244963224,
   'predicted_binding_rate': 0.05532459226095299},
  '2024-09-28': {'mae': 53.850972738601705,
   'rmse': np.float64(366.07769275071206),
   'mape': np.float64(169.38452877210207),
   'precision': 0.1424,
   'recall': 0.2479108635097493,
   'f1_score': 0.18089430894308944,
   'accuracy': np.float64(0.935370058535803),
   'true_positives': 89,
   'false_positives': 536,
   'true_negatives': 11576,
   'false_negatives': 270,
   'total_samples': 12471,
   'actual_binding_count': 359,
   'predicted_binding_count': 625,
   'actual_binding_rate': 0.028786785341993425,
   'predicted_binding_rate': 0.05011626974581028},
  '2024-10-01': {'mae': 109.38782416177906,
   'rmse': np.float64(638.5367899195393),
   'mape': np.float64(380.0108101408707),
   'precision': 0.22661396574440051,
   'recall': 0.2783171521035599,
   'f1_score': 0.24981844589687727,
   'accuracy': np.float64(0.9161662067846129),
   'true_positives': 172,
   'false_positives': 587,
   'true_negatives': 11117,
   'false_negatives': 446,
   'total_samples': 12322,
   'actual_binding_count': 618,
   'predicted_binding_count': 759,
   'actual_binding_rate': 0.0501541957474436,
   'predicted_binding_rate': 0.06159714332088947},
  '2024-10-04': {'mae': 67.45219089574512,
   'rmse': np.float64(476.9364973860231),
   'mape': np.float64(2230.624689842923),
   'precision': 0.12424242424242424,
   'recall': 0.21298701298701297,
   'f1_score': 0.1569377990430622,
   'accuracy': np.float64(0.9289458827324785),
   'true_positives': 82,
   'false_positives': 578,
   'true_negatives': 11436,
   'false_negatives': 303,
   'total_samples': 12399,
   'actual_binding_count': 385,
   'predicted_binding_count': 660,
   'actual_binding_rate': 0.031050891200903298,
   'predicted_binding_rate': 0.05323009920154851},
  '2024-10-07': {'mae': 74.96855422376211,
   'rmse': np.float64(603.218008443903),
   'mape': np.float64(754.3944655576462),
   'precision': 0.19664634146341464,
   'recall': 0.3282442748091603,
   'f1_score': 0.2459485224022879,
   'accuracy': np.float64(0.9357224118316269),
   'true_positives': 129,
   'false_positives': 527,
   'true_negatives': 11386,
   'false_negatives': 264,
   'total_samples': 12306,
   'actual_binding_count': 393,
   'predicted_binding_count': 656,
   'actual_binding_rate': 0.031935641150658216,
   'predicted_binding_rate': 0.05330732975784171},
  '2024-10-10': {'mae': 69.20251917703297,
   'rmse': np.float64(506.3740741350327),
   'mape': np.float64(372.76881651052463),
   'precision': 0.2119309262166405,
   'recall': 0.3253012048192771,
   'f1_score': 0.25665399239543724,
   'accuracy': np.float64(0.9366801619433198),
   'true_positives': 135,
   'false_positives': 502,
   'true_negatives': 11433,
   'false_negatives': 280,
   'total_samples': 12350,
   'actual_binding_count': 415,
   'predicted_binding_count': 637,
   'actual_binding_rate': 0.03360323886639676,
   'predicted_binding_rate': 0.05157894736842105},
  '2024-10-13': {'mae': 82.21628713313521,
   'rmse': np.float64(518.570434272461),
   'mape': np.float64(996.4189790549209),
   'precision': 0.22629969418960244,
   'recall': 0.2824427480916031,
   'f1_score': 0.25127334465195245,
   'accuracy': np.float64(0.9287560581583199),
   'true_positives': 148,
   'false_positives': 506,
   'true_negatives': 11350,
   'false_negatives': 376,
   'total_samples': 12380,
   'actual_binding_count': 524,
   'predicted_binding_count': 654,
   'actual_binding_rate': 0.04232633279483037,
   'predicted_binding_rate': 0.05282714054927302},
  '2024-10-16': {'mae': 99.81643173265617,
   'rmse': np.float64(655.3883610449178),
   'mape': np.float64(415.6081059804268),
   'precision': 0.2707993474714519,
   'recall': 0.2577639751552795,
   'f1_score': 0.26412092283214,
   'accuracy': np.float64(0.9251557569382636),
   'true_positives': 166,
   'false_positives': 447,
   'true_negatives': 11268,
   'false_negatives': 478,
   'total_samples': 12359,
   'actual_binding_count': 644,
   'predicted_binding_count': 613,
   'actual_binding_rate': 0.0521077757100089,
   'predicted_binding_rate': 0.04959948215875071},
  '2024-10-19': {'mae': 78.46083931736433,
   'rmse': np.float64(455.5439455547417),
   'mape': np.float64(359.38067821275115),
   'precision': 0.289193302891933,
   'recall': 0.3125,
   'f1_score': 0.30039525691699603,
   'accuracy': np.float64(0.9284617250020208),
   'true_positives': 190,
   'false_positives': 467,
   'true_negatives': 11296,
   'false_negatives': 418,
   'total_samples': 12371,
   'actual_binding_count': 608,
   'predicted_binding_count': 657,
   'actual_binding_rate': 0.04914719909465686,
   'predicted_binding_rate': 0.053108075337482824},
  '2024-10-22': {'mae': 81.36387782791468,
   'rmse': np.float64(482.5299125897211),
   'mape': np.float64(729.0394250631084),
   'precision': 0.3203732503888025,
   'recall': 0.2728476821192053,
   'f1_score': 0.2947067238912732,
   'accuracy': np.float64(0.9202587949858472),
   'true_positives': 206,
   'false_positives': 437,
   'true_negatives': 11173,
   'false_negatives': 549,
   'total_samples': 12365,
   'actual_binding_count': 755,
   'predicted_binding_count': 643,
   'actual_binding_rate': 0.06105944197331177,
   'predicted_binding_rate': 0.05200161746866155},
  '2024-10-25': {'mae': 72.56956359583826,
   'rmse': np.float64(463.61966359536945),
   'mape': np.float64(557.1928425271109),
   'precision': 0.2643856920684292,
   'recall': 0.3269230769230769,
   'f1_score': 0.292347377472055,
   'accuracy': np.float64(0.9335271787416203),
   'true_positives': 170,
   'false_positives': 473,
   'true_negatives': 11388,
   'false_negatives': 350,
   'total_samples': 12381,
   'actual_binding_count': 520,
   'predicted_binding_count': 643,
   'actual_binding_rate': 0.04199983846215976,
   'predicted_binding_rate': 0.051934415636862935},
  '2024-10-28': {'mae': 110.51541657782488,
   'rmse': np.float64(753.7581314691922),
   'mape': np.float64(48669.97092120194),
   'precision': 0.2626427406199021,
   'recall': 0.24807395993836673,
   'f1_score': 0.2551505546751189,
   'accuracy': np.float64(0.924358252192806),
   'true_positives': 161,
   'false_positives': 452,
   'true_negatives': 11326,
   'false_negatives': 488,
   'total_samples': 12427,
   'actual_binding_count': 649,
   'predicted_binding_count': 613,
   'actual_binding_rate': 0.05222499396475416,
   'predicted_binding_rate': 0.049328075963627586},
  '2024-10-31': {'mae': 61.341728966845075,
   'rmse': np.float64(505.9226631613899),
   'mape': np.float64(2580.7269184048196),
   'precision': 0.1761744966442953,
   'recall': 0.3804347826086957,
   'f1_score': 0.2408256880733945,
   'accuracy': np.float64(0.9468614544870766),
   'true_positives': 105,
   'false_positives': 491,
   'true_negatives': 11691,
   'false_negatives': 171,
   'total_samples': 12458,
   'actual_binding_count': 276,
   'predicted_binding_count': 596,
   'actual_binding_rate': 0.022154438914753573,
   'predicted_binding_rate': 0.047840744902873655},
  '2024-11-01': {'mae': 83.19561369636443,
   'rmse': np.float64(732.5754732219052),
   'mape': np.float64(455.7194428947592),
   'precision': 0.26424870466321243,
   'recall': 0.2688927943760984,
   'f1_score': 0.2665505226480836,
   'accuracy': np.float64(0.9320364839777222),
   'true_positives': 153,
   'false_positives': 426,
   'true_negatives': 11394,
   'false_negatives': 416,
   'total_samples': 12389,
   'actual_binding_count': 569,
   'predicted_binding_count': 579,
   'actual_binding_rate': 0.04592783921220438,
   'predicted_binding_rate': 0.046735006860925014},
  '2024-11-04': {'mae': 97.36669357048753,
   'rmse': np.float64(787.723729225333),
   'mape': np.float64(1019.7250648859924),
   'precision': 0.25688073394495414,
   'recall': 0.2809364548494983,
   'f1_score': 0.268370607028754,
   'accuracy': np.float64(0.9250960830812004),
   'true_positives': 168,
   'false_positives': 486,
   'true_negatives': 11145,
   'false_negatives': 430,

In [ ]:
results_per_outage[results_per_outage['market_month'] == '2025-11'].xs('316316', level='constraint_id')

,70_diff,90,105,curvature_100,80_diff,95,prob_exceed_100,prob_exceed_90,prob_overload,season_cos,forecast_horizon,100_diff,100,95_diff,85_diff,110,risk_ratio,log_density_100,60_diff,season_sin,90_diff,105_diff,actual_shadow_price,branch_name,outage_date,auction_month,market_month,predicted_shadow_price,binding_probability,binding_probability_scaled,threshold,predicted_binding,model_used,actual_binding
flow_direction,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1.784015,3.258502,5.754621,-0.148212,2.640703,3.908352,8.430245,7.388001,8.430245,1.250873,-0.371556,5.138524,4.505723,4.280096,3.077991,6.537937,-0.002386,4.963730,0.926014,-1.162754,3.615944,6.282474,3622.70,AUST_TAYS_1545 A,2025-11-01,2025-10-01,2025-11-01,910.410828,0.997876,0.997876,0.5,1,Anomaly: AUST_TAYS_1545 A,1
1,1.734512,3.213132,5.700590,-0.449658,2.599568,3.863028,8.784135,7.622319,8.784135,1.250873,-0.371556,5.156673,4.578977,4.288577,3.039562,6.515162,-0.002385,5.023914,0.882424,-1.162754,3.569837,6.241609,8037.55,AUST_TAYS_1545 A,2025-11-04,2025-10-01,2025-11-01,864.286865,1.000000,1.000000,0.5,1,Anomaly: AUST_TAYS_1545 A,1
1,1.862594,3.459646,5.726164,-0.247413,2.660966,4.022102,7.835947,7.050664,7.835947,1.250873,-0.371556,5.276386,4.767611,4.465211,3.143225,6.787118,-0.002388,5.176953,0.908692,-1.162754,3.779701,6.383535,1638.56,AUST_TAYS_1545 A,2025-11-07,2025-10-01,2025-11-01,992.354065,1.000000,1.000000,0.5,1,Anomaly: AUST_TAYS_1545 A,1
1,1.759646,3.039187,5.304565,-0.423014,2.416127,3.556261,7.938228,6.943010,7.938228,1.250873,-0.371556,4.892203,4.424071,4.044664,2.833966,6.452069,-0.002386,4.896139,0.793799,-1.162754,3.331057,5.990821,5366.23,AUST_TAYS_1545 A,2025-11-10,2025-10-01,2025-11-01,835.852417,0.993511,0.993511,0.5,1,Anomaly: AUST_TAYS_1545 A,1
1,1.499928,3.075816,5.564916,0.090726,2.370683,3.617446,9.700059,8.159123,9.700059,1.250873,-0.371556,4.933825,4.295742,4.019583,2.898123,6.569988,-0.002380,4.788806,0.706745,-1.162754,3.379748,6.191569,2126.53,AUST_TAYS_1545 A,2025-11-13,2025-10-01,2025-11-01,1077.029053,0.986651,0.986651,0.5,1,Anomaly: AUST_TAYS_1545 A,1
1,-0.471639,-0.320627,-0.216123,-0.131973,-0.393982,-0.276470,-0.182346,-0.242497,-0.182346,1.250873,-0.371556,-0.232826,-0.238561,-0.265645,-0.349425,-0.181014,-0.002412,-0.283252,-0.588884,-1.162754,-0.305396,-0.205661,0.00,AUST_TAYS_1545 A,2025-11-16,2025-10-01,2025-11-01,0.000000,0.000000,0.000000,0.5,0,Never-Binding: AUST_TAYS_1545 A,0
1,-0.471639,-0.320627,-0.216123,-0.131973,-0.393982,-0.276470,-0.182346,-0.242497,-0.182346,1.250873,-0.371556,-0.232826,-0.238561,-0.265645,-0.349425,-0.181014,-0.002412,-0.283252,-0.588884,-1.162754,-0.305396,-0.205661,0.00,AUST_TAYS_1545 A,2025-11-19,2025-10-01,2025-11-01,0.000000,0.000000,0.000000,0.5,0,Never-Binding: AUST_TAYS_1545 A,0
1,1.683353,3.157262,5.500393,-0.572884,2.254989,3.834945,6.262102,5.856624,6.262102,1.250873,-0.371556,4.926953,4.333540,4.159164,2.827407,5.738423,-0.002390,4.820561,1.009203,-1.162754,3.525989,5.765238,0.00,AUST_TAYS_1545 A,2025-11-22,2025-10-01,2025-11-01,869.166748,0.988672,0.988672,0.5,1,Anomaly: AUST_TAYS_1545 A,0
1,1.664688,3.139190,5.396115,-0.318122,2.289832,3.745347,6.177483,5.768200,6.177483,1.250873,-0.371556,4.817300,4.223107,4.057738,2.835403,5.732501,-0.002391,4.727447,1.019168,-1.162754,3.474266,5.704220,0.00,AUST_TAYS_1545 A,2025-11-25,2025-10-01,2025-11-01,833.698486,0.982768,0.982768,0.5,1,Anomaly: AUST_TAYS_1545 A,0
1,1.718348,3.249650,5.448256,-0.947235,2.286570,3.727268,5.985168,5.675479,5.985168,1.250873,-0.371556,5.038407,4.567726,4.207168,2.887829,5.823683,-0.002392,5.014699,1.054442,-1.162754,3.526641,5.776137,0.00,AUST_TAYS_1545 A,2025-11-28,2025-10-01,2025-11-01,920.906555,1.000000,1.000000,0.5,1,Anomaly: AUST_TAYS_1545 A,0

In [ ]:
final_results.xs('316316', level='constraint_id')

,branch_name,105,80_diff,prob_exceed_100,100_diff,curvature_100,log_density_100,100,105_diff,risk_ratio,season_cos,95,85_diff,season_sin,90_diff,60_diff,95_diff,forecast_horizon,70_diff,110,90,prob_overload,prob_exceed_90,actual_shadow_price,predicted_shadow_price,binding_probability,binding_probability_scaled,threshold,predicted_binding_count,actual_binding,auction_month,market_month,model_used,predicted_binding,error,abs_error
flow_direction,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,AUST_TAYS_1545 A,-0.222676,-0.396567,-0.189749,-0.240615,-0.132835,-0.291872,-0.247593,-0.213415,-0.003436,-1.638969,-0.287794,-0.359034,-0.302390,-0.314818,-0.572481,-0.274367,-0.978030,-0.473142,-0.190663,-0.328508,-0.189749,-0.250259,0.00,0.000000,0.000000,0.000000,0.5,0,0,2025-06-01,2025-06-01,Never-Binding: AUST_TAYS_1545 A,False,0.000000,0.000000
1,AUST_TAYS_1545 A,-0.222891,-0.388058,-0.189902,-0.240680,-0.129611,-0.291613,-0.247692,-0.213674,-0.003438,-1.441020,-0.286328,-0.347425,-1.022871,-0.312816,-0.541009,-0.273542,-0.977787,-0.457775,-0.191285,-0.326137,-0.189902,-0.249779,0.00,0.000000,0.000000,0.000000,0.5,0,0,2025-07-01,2025-07-01,Never-Binding: AUST_TAYS_1545 A,False,0.000000,0.000000
1,AUST_TAYS_1545 A,-0.222892,-0.399015,-0.189920,-0.240763,-0.134025,-0.291833,-0.247836,-0.213674,-0.003438,-0.902305,-0.287665,-0.355453,-1.550330,-0.314779,-0.555862,-0.274351,-0.586052,-0.466436,-0.191285,-0.328569,-0.189920,-0.250377,0.00,0.000000,0.000000,0.000000,0.5,0,0,2025-07-01,2025-08-01,Never-Binding: AUST_TAYS_1545 A,False,0.000000,0.000000
1,AUST_TAYS_1545 A,1.750061,1.255955,1.999085,1.717400,0.003636,1.929407,1.642664,1.824497,-0.003417,-0.166407,1.566034,1.435103,-1.743393,1.544866,0.531110,1.629355,-0.194316,0.904382,1.819975,1.483169,1.999085,2.010755,0.00,3093.115051,0.517068,0.517068,0.5,5,0,2025-07-01,2025-09-01,Never-Binding: AUST_TAYS_1545 A,True,3093.115051,3093.115051
1,AUST_TAYS_1545 A,3.587550,2.317973,4.510896,3.417564,-0.155593,3.727192,3.186764,3.760944,-0.003389,0.569491,2.868534,2.587164,-1.550330,2.812326,1.132692,3.066830,0.197420,1.814445,3.775946,2.685187,4.510896,4.275150,2950.54,10312.792114,0.932455,0.932455,0.5,11,1,2025-07-01,2025-10-01,Anomaly: AUST_TAYS_1545 A,True,7362.252114,7362.252114
1,AUST_TAYS_1545 A,3.988913,1.834263,5.583727,3.670722,-0.253874,3.659353,3.316810,4.425398,-0.003382,1.108206,2.765243,2.227568,-1.022871,2.602017,0.589885,3.069682,0.589156,1.272798,4.726376,2.391090,5.583727,4.962689,20791.57,0.000000,0.790102,0.790102,0.5,8,1,2025-07-01,2025-11-01,Anomaly: AUST_TAYS_1545 A,True,-20791.570000,20791.570000

In [ ]:
final_results.sort_values(['actual_shadow_price', 'binding_probability_scaled'], ascending=False).drop_duplicates(subset=['branch_name', 'auction_month']).head(20)

,,branch_name,log_density_100,95_diff,105_diff,100_diff,95,80_diff,90_diff,prob_overload,prob_exceed_90,prob_exceed_100,70_diff,85_diff,110,105,curvature_100,90,60_diff,100,risk_ratio,actual_shadow_price,predicted_shadow_price,binding_probability,binding_probability_scaled,threshold,predicted_binding_count,actual_binding,auction_month,market_month,model_used,predicted_binding,error,abs_error
constraint_id,flow_direction,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
322296,1,FORMAFORMN11_1 1,-0.298647,-0.277988,-0.218690,-0.246380,-0.286987,-0.355082,-0.311701,-0.193522,-0.252338,-0.193522,-0.398123,-0.339996,-0.188941,-0.231566,-0.111418,-0.322911,-0.304735,-0.248626,-0.002476,59113.56,19572.664551,0.755965,0.530701,0.74,11,1,2025-10-01,2025-10-01,Branch: FORMAFORMN11_1 1,True,-39540.895449,39540.895449
373761,1,GOOSEMNPIP11_1 1,-0.298647,-0.277990,-0.218690,-0.246380,-0.286990,-0.404167,-0.316386,-0.193522,-0.253349,-0.193522,-0.483452,-0.358930,-0.188941,-0.231566,-0.127217,-0.331435,-0.600108,-0.248626,-0.002476,49015.21,0.000000,0.040880,0.021516,0.95,0,1,2025-10-01,2025-10-01,Branch: GOOSEMNPIP11_1 1,False,-49015.210000,49015.210000
191486,1,NEBRCSUB3434_1 1,-0.168057,-0.193604,-0.187109,-0.183987,-0.208883,0.050854,-0.212375,-0.174093,-0.201605,-0.174093,0.284406,-0.120213,-0.160122,-0.199768,-0.092672,-0.209068,0.579188,-0.165461,-0.009854,45969.48,3591.270874,0.445176,0.339059,0.67,2,1,2025-08-01,2025-08-01,Branch: NEBRCSUB3434_1 1,True,-42378.209126,42378.209126
276166,1,MNTCELO TR6__2,5.864989,6.217540,5.819640,6.139771,6.060308,4.987471,6.063371,3.857620,5.132705,3.857620,3.730285,5.555863,5.115379,6.055116,-0.221620,5.875901,2.122431,5.961734,-0.002474,41374.66,3245.228394,0.170138,0.170138,0.50,2,1,2025-11-01,2025-11-01,Anomaly: MNTCELO TR6__2,True,-38129.431606,38129.431606
233584,1,BIGSTBROWN23_1 1,0.983481,0.869712,0.394810,0.615527,0.935809,1.732736,1.212618,0.238637,0.587311,0.238637,2.303848,1.553061,0.321171,0.434017,0.977879,1.410276,2.431939,0.728137,-0.002482,37863.92,8389.231873,0.744353,0.581395,0.70,8,1,2025-11-01,2025-11-01,Branch: BIGSTBROWN23_1 1,True,-29474.688127,29474.688127
337116,1,MRYVLBRADD16_1 1,0.351470,0.178229,0.181563,0.198473,0.161653,0.027477,0.123208,0.115154,0.138687,0.115154,0.014836,0.062438,0.146684,0.201199,-0.215639,0.087242,0.117517,0.189641,-0.009706,28938.79,3379.974396,0.613861,0.458962,0.70,6,1,2025-07-01,2025-07-01,Branch: MRYVLBRADD16_1 1,True,-25558.815604,25558.815604
121700,-1,ULRICMAHNO11_1 1,0.296960,0.250742,0.178339,0.217300,0.265963,0.209076,0.277268,0.085288,0.164429,0.085288,0.080594,0.251096,0.131488,0.208885,0.064029,0.278146,-0.136753,0.215745,-0.002455,26006.01,0.000000,0.226617,0.147154,0.77,0,1,2025-10-01,2025-10-01,Branch: ULRICMAHNO11_1 1,False,-26006.010000,26006.010000
232780,1,RILLA__RIVTON3 A,5.368736,5.474837,5.491588,5.374908,5.503908,4.517072,5.405215,5.150349,5.746467,5.150349,3.200098,5.086503,5.085989,5.511927,0.698298,5.150596,1.609185,5.074117,-0.002459,25956.94,6012.525391,0.477386,0.350037,0.69,2,1,2025-10-01,2025-10-01,Branch: RILLA__RIVTON3 A,True,-19944.414609,19944.414609
430652,1,ROSEHURON23_1 1,0.321483,0.271129,-0.045270,0.092041,0.340501,0.969207,0.493305,-0.067443,0.108055,-0.067443,1.155740,0.788643,-0.076464,-0.014791,0.611249,0.607867,1.321066,0.169871,-0.002474,25655.66,8252.693359,0.532465,0.445224,0.62,3,1,2025-10-01,2025-10-01,Branch: ROSEHURON23_1 1,True,-17402.966641,17402.966641
295336,1,NEBRCSUB3434_1 1,0.956081,0.749946,0.733763,0.762049,0.722434,0.870466,0.773028,0.521025,0.664926,0.521025,0.968203,0.817161,0.652927,0.761999,0.108726,0.790647,1.064746,0.735404,-0.002623,23306.94,26671.148804,0.678205,0.558038,0.66,8,1,2025-09-01,2025-09-01,Branch: NEBRCSUB3434_1 1,True,3364.208804,3364.208804
363301,1,TEKAMSUB1216_1 1,-0.209807,-0.219747,-0.194797,-0.197935,-0.233497,-0.101433,-0.243375,-0.178792,-0.216223,-0.178792,0.421242,-0.235813,-0.180829,-0.195022,-0.099412,-0.244465,0.653159,-0.193052,-0.009745,22514.97,2253.775574,0.592658,0.436646,0.69,2,1,2025-06-01,2025-06-01,Branch: TEKAMSUB1216_1 1,True,-20261.194426,20261.194426
310876,1,SHRMNSTSUNNY 1,0.355788,0.237702,0.105553,0.196860,0.246754,0.336934,0.298779,0.021322,0.122126,0.021322,0.355569,0.311753,0.027340,0.168173,0.085113,0.333109,0.347943,0.211846,-0.002625,20918.09,10784.356812,0.419132,0.388269,0.66,4,1,2025-09-01,2025-09-01,Branch: SHRMNSTSUNNY 1,True,-10133.733188,10133.733188
316316,1,AUST_TAYS_1545 A,3.817740,3.290423,4.379179,3.847400,2.986756,1.892581,2.809593,4.024359,4.012711,4.024359,1.387596,2.341735,4.230907,4.213496,-0.452925,2.570680,0.771567,3.419806,-0.002463,20791.57,2811.193237,0.513453,0.380604,0.68,2,1,2025-11-01,2025-11-01,Branch: AUST_TAYS_1545 A,True,-17980.376763,17980.376763
314718,1,FORMAFORMN11_1 1,-0.301912,-0.281169,-0.221801,-0.249317,-0.290657,-0.407531,-0.319431,-0.196699,-0.256632,-0.196699,-0.486578,-0.362307,-0.192863,-0.234296,-0.126007,-0.333379,-0.603436,-0.252042,-0.002628,20427.08,23980.319824,0.751550,0.522212,0.74,10,1,2025-09-01,2025-09-01,Branch: FORMAFORMN11_1 1,True,3553.239824,3553.239824
128378,1,15616 1,-0.307299,-0.286488,-0.226048,-0.252994,-0.300095,-0.417574,-0.328116,-0.201303,-0.262207,-0.201303,-0.488025,-0.373025,-0.198199,-0.236277,-0.126324,-0.341969,-0.579926,-0.256759,-0.009753,19693.05,0.000000,0.620400,0.492381,0.63,0,1,2025-06-01,2025-06-01,Branch: 15616 1,False,-19693.050000,19693.050000
28297,1,PENN_LEEDS11_1 1,1.423046,1.203429,0.702577,0.991789,1.247173,1.837148,1.439428,0.395143,0.802718,0.395143,2.007285,1.645227,0.498321,0.840381,0.509785,1.557731,1.807992,1.070579,-0.002472,19450.78,24114.679932,0.791786,0.735527,0.65,8,1,2025-10-01,2025-10-01,Branch: PENN_LEEDS11_1 1,True,4663.899932,4663.899932
411698,1,MORRIGRANT11_1 1,0.714697,0.693081,0.188372,0.386533,0.842812,1.770177,1.069228,0.076166,0.408412,0.076166,2.148391,1.436312,0.092680,0.261637,1.127917,1.228304,2.180906,0.467318,-0.002474,19258.65,5186.795654,0.602744,0.450089,0.70,5,1,2025-10-01,2025-10-01,Branch: MORRIGRANT11_1 1,True,-14071.854346,14071.854346
430652,1,ROSEHURON23_1 1,0.011282,-0.018967,-0.058404,-0.019608,0.004578,0.128162,-0.020761,-0.107864,-0.082631,-0.107864,0.179329,0.029804,-0.141444,0.015357,-0.079581,-0.041472,0.161909,-0.045945,-0.009750,18905.49,1171.930176,0.506508,0.379419,0.68,1,1,2025-07-01,2025-07-01,Branch: ROSEHURON23_1 1,True,-17733.559824,17733.559824
314718,1,FORMAFORMN11_1 1,-0.307758,-0.286758,-0.227063,-0.253810,-0.299853,-0.416706,-0.327427,-0.201998,-0.262637,-0.201998,-0.496493,-0.371950,-0.200491,-0.237135,-0.127356,-0.341017,-0.613986,-0.258084,-0.009766,18498.70,27253.633301,0.764065,0.546278,0.74,11,1,2025-07-01,2025-07-01,Branch: FORMAFORMN11_1 1,True,8754.933301,8754.933301
3816,1,WILMAEASTW11_1 1,1.640313,1.508869,1.414563,1.425100,1.562650,2.268623,1.769916,1.104676,1.420663,1.104676,2.540127,2.022702,1.295879,1.436462,1.053698,1.892460,2.504514,1.366769,-0.009831,17658.79,986.525146,0.080116,0.080116,0.50,1,1,2025-08-01,2025-08-01,Never-Binding: WILMAEASTW11_1 1,True,-16672.264854,16672.264854